package com.doom.gateway;

/**
 * Generates the HTML for the DOOM session landing page served at /system/doom/.
 *
 * <p>The page lets users start single-player or deathmatch sessions and view active sessions.
 * All live data is fetched client-side from /system/doom/health via JS polling — no separate
 * data endpoint is needed. Branding images are served from /system/doom/branding/{file} and
 * fail silently via onerror if the branding directory has not been populated.
 */
public class DoomLandingPage {

    public static String getHTML(java.util.List<String> brandingFiles) {
        // Build branding <img> tags from the server-side file list
        StringBuilder brandImgHtml = new StringBuilder();
        for (String bf : brandingFiles) {
            brandImgHtml.append("    <img class='branding-logo'")
                        .append(" src='/system/doom/branding/").append(bf).append("'")
                        .append(" alt='' onerror='this.style.display=&quot;none&quot;;checkBrandingEmpty()'>\n");
        }
        int brandTotal = brandingFiles.size();
        String brandingRow = brandTotal > 0
            ? "  <div class='branding-row' id='brandingRow'>\n" + brandImgHtml + "  </div>\n"
            : "";

        return "<!DOCTYPE html><html lang='en'>\n"
            + "<head><meta charset='UTF-8'>"
            + "<meta name='viewport' content='width=device-width,initial-scale=1'>"
            + "<title>Ignition DOOM</title>\n"
            + "<style>\n"
            + "* { box-sizing: border-box; margin: 0; padding: 0; }\n"
            + "body { background: #0d0d0d; color: #c8c8c8; font-family: 'Courier New', monospace; padding: 24px; min-height: 100vh; }\n"

            // Header
            + ".header { border-bottom: 1px solid #333; padding-bottom: 14px; margin-bottom: 8px; }\n"
            + ".header-row { display: flex; align-items: center; gap: 18px; }\n"
            + ".header-logo { height: 110px; width: auto; border-radius: 3px; opacity: 0.92; }\n"
            + ".header-text { display: flex; flex-direction: column; justify-content: center; gap: 6px; }\n"
            + ".header-title { color: #ff4444; font-size: 28px; font-weight: bold; text-transform: uppercase; letter-spacing: 6px; line-height: 1; }\n"
            + ".header-desc { color: #888; font-size: 11px; letter-spacing: 2px; text-transform: uppercase; }\n"

            // Branding row
            + ".branding-row { display: flex; align-items: center; gap: 32px; margin-top: 10px; padding-top: 10px; border-top: 1px solid #1e1e1e; min-height: 0; }\n"
            + ".branding-logo { height: 26px; width: auto; opacity: 0.55; }\n"
            + ".branding-sep { color: #333; }\n"

            // Stats bar
            + ".stats-bar { display: flex; align-items: center; flex-wrap: wrap; color: #999; font-size: 12px; margin: 10px 0 22px 0; }\n"
            + ".stats-bar .sep { margin: 0 10px; color: #444; }\n"
            + ".stat-engines.full .used { color: #ff4444; }\n"
            + ".stat-links { margin-left: auto; display: flex; gap: 14px; }\n"
            + ".stat-link { color: #666; font-size: 11px; text-decoration: none; letter-spacing: 1px; text-transform: uppercase; }\n"
            + ".stat-link:hover { color: #aaa; }\n"

            // Cap warning
            + ".cap-warning { background: #1a0a00; border: 1px solid #663300; color: #ff8844; padding: 9px 16px; font-size: 12px; margin-bottom: 18px; letter-spacing: 1px; }\n"
            + ".cap-warning.hidden { display: none; }\n"

            // Action cards
            + ".cards { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 32px; }\n"
            + "@media (max-width: 640px) { .cards { grid-template-columns: 1fr; } }\n"
            + ".card { background: #111; border: 1px solid #2a2a2a; padding: 20px 22px; }\n"
            + ".card.disabled { opacity: 0.45; pointer-events: none; }\n"
            + ".card-title { color: #ff4444; font-size: 13px; font-weight: bold; text-transform: uppercase; letter-spacing: 3px; margin-bottom: 18px; padding-bottom: 10px; border-bottom: 1px solid #2a2a2a; }\n"
            + ".field { margin-bottom: 14px; }\n"
            + ".field label { display: block; color: #aaa; font-size: 12px; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 6px; }\n"
            + ".select-wrap { position: relative; }\n"
            + ".select-wrap::after { content: '\\25BE'; position: absolute; right: 10px; top: 50%; transform: translateY(-50%); color: #666; pointer-events: none; font-size: 12px; }\n"
            + "select { background: #0d0d0d; border: 1px solid #383838; color: #c8c8c8; font-family: 'Courier New', monospace; font-size: 13px; padding: 7px 10px; width: 100%; appearance: none; -webkit-appearance: none; cursor: pointer; outline: none; }\n"
            + "select:focus { border-color: #ff4444; }\n"
            + "select option { background: #111; }\n"
            + ".btn { display: block; width: 100%; background: #7a0000; color: #ffcccc; border: 1px solid #cc0000; font-family: 'Courier New', monospace; font-size: 12px; font-weight: bold; text-transform: uppercase; letter-spacing: 3px; padding: 10px 0; cursor: pointer; margin-top: 18px; outline: none; }\n"
            + ".btn:hover { background: #cc0000; color: #fff; }\n"
            + ".btn:disabled { opacity: 0.4; cursor: not-allowed; }\n"
            + ".match-id-input { width:100%; background:#1a1a1a; color:#ccc; border:1px solid #333; font-family:'Courier New',monospace; font-size:13px; padding:8px 10px; outline:none; text-transform:uppercase; letter-spacing:1px; }\n"
            + ".match-id-input:focus { border-color:#ff4444; }\n"
            + ".match-id-input::placeholder { color:#444; text-transform:none; letter-spacing:0; }\n"
            + ".match-id-hint { font-size:11px; color:#777; margin-top:4px; }\n"
            + ".detect-badge { display:none; align-items:center; gap:6px; margin-top:6px; padding:5px 10px; background:#1f0a0a; border:1px solid #5a1a1a; color:#cc7777; font-size:11px; letter-spacing:0.5px; }\n"
            + ".detect-badge.visible { display:inline-flex; }\n"
            + ".detect-badge .db-icon { color:#cc3333; }\n"
            + ".detect-badge .db-name { color:#ee9999; font-weight:bold; }\n"
            + ".detect-badge.unavailable { border-color:#3a3a1a; background:#1a1a0a; color:#888; }\n"
            + ".detect-badge.unavailable .db-icon,.detect-badge.unavailable .db-name { color:#888; }\n"
            + "@keyframes flash-wad { 0%{border-color:#cc0000;box-shadow:0 0 6px #cc000055} 100%{border-color:#333;box-shadow:none} }\n"
            + ".wad-flash select { animation:flash-wad 1.2s ease-out forwards; }\n"

            // Sections
            + ".section-header { display: flex; align-items: baseline; gap: 12px; margin-bottom: 10px; }\n"
            + ".section-title { color: #ff4444; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 3px; }\n"
            + ".section-count { color: #555; font-size: 11px; }\n"

            // Tables
            + "table { border-collapse: collapse; width: 100%; margin-bottom: 28px; }\n"
            + "th { color: #ff4444; text-align: left; padding: 7px 14px; border-bottom: 2px solid #ff4444; text-transform: uppercase; letter-spacing: 2px; font-size: 10px; }\n"
            + "td { padding: 8px 14px; border-bottom: 1px solid #1c1c1c; font-size: 12px; vertical-align: middle; }\n"
            + "tr:hover td { background: #131313; }\n"
            + ".empty-row td { color: #444; padding: 20px 14px; text-align: center; }\n"
            + "tr:hover.empty-row td { background: transparent; }\n"

            // Cell types
            + ".cell-id { color: #6688bb; font-size: 11px; cursor: pointer; user-select: all; }\n"
            + ".cell-id:hover { color: #88aadd; }\n"
            + ".cell-wad { color: #ffcc00; }\n"
            + ".cell-time { color: #aaa; }\n"
            + ".cell-status-running { color: #44cc44; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; }\n"
            + ".cell-status-lobby { color: #ffaa00; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; }\n"
            + ".cell-players .joined { color: #44cc44; }\n"
            + ".cell-players .waiting { color: #ffaa00; }\n"
            + ".join-link { background: #003300; color: #88ee88; border: 1px solid #006600; padding: 4px 12px; text-decoration: none; font-size: 10px; letter-spacing: 1px; text-transform: uppercase; white-space: nowrap; }\n"
            + ".join-link:hover { background: #004400; color: #aaffaa; }\n"
            + ".join-link.full { background: #1a1a1a; color: #555; border-color: #333; pointer-events: none; }\n"

            // Footer
            + ".footer { border-top: 1px solid #1a1a1a; padding-top: 14px; margin-top: 8px; }\n"
            + ".footer-note { color: #333; font-size: 10px; letter-spacing: 1px; }\n"

            // Copy flash
            + ".copied-flash { color: #44cc44; font-size: 10px; margin-left: 6px; opacity: 0; transition: opacity 0.2s; }\n"
            + ".copied-flash.show { opacity: 1; }\n"

            // Auth overlay
            + "#authOverlay { display:none; position:fixed; inset:0; background:rgba(0,0,0,0.94); z-index:200; align-items:center; justify-content:center; }\n"
            + "#authOverlay.visible { display:flex; }\n"
            + ".auth-box { background:#111; border:1px solid #3a0000; padding:40px 44px; text-align:center; max-width:340px; width:100%; }\n"
            + ".auth-title { color:#ff4444; font-size:14px; font-weight:bold; text-transform:uppercase; letter-spacing:4px; margin-bottom:8px; }\n"
            + ".auth-sub { color:#555; font-size:11px; letter-spacing:1px; margin-bottom:24px; }\n"
            + ".auth-input { width:100%; background:#0d0d0d; border:1px solid #383838; color:#c8c8c8; font-family:'Courier New',monospace; font-size:15px; letter-spacing:3px; padding:10px 14px; outline:none; text-align:center; margin-bottom:14px; }\n"
            + ".auth-input:focus { border-color:#ff4444; }\n"
            + ".auth-err { color:#c0392b; font-size:11px; min-height:16px; margin-top:6px; letter-spacing:1px; }\n"
            + "</style></head>\n"
            + "<body>\n"

            // Auth overlay element
            + "<div id='authOverlay'>\n"
            + "  <div class='auth-box'>\n"
            + "    <div class='auth-title'>&#128274; Access Required</div>\n"
            + "    <div class='auth-sub'>Enter the play password to continue</div>\n"
            + "    <input class='auth-input' type='password' id='authPw' placeholder='PASSWORD'\n"
            + "           autocomplete='off' onkeydown='if(event.key===\"Enter\")submitAuth();'/>\n"
            + "    <button class='btn' onclick='submitAuth()'>Enter</button>\n"
            + "    <div class='auth-err' id='authErr'></div>\n"
            + "  </div>\n"
            + "</div>\n"

            // ── Header
            + "<div class='header'>\n"
            + "  <div class='header-row'>\n"
            + "    <img class='header-logo' src='/system/doom/static/doom-logo.png' alt='DOOM'>\n"
            + "    <div class='header-text'>\n"
            + "      <div class='header-title'>Ignition DOOM</div>\n"
            + "      <div class='header-desc'>Perspective Gateway Module</div>\n"
            + "    </div>\n"
            + "  </div>\n"
            // Branding row — dynamically populated from server-side file list; omitted if empty
            + brandingRow
            + "</div>\n"

            // ── Stats bar
            + "<div class='stats-bar'>\n"
            + "  <span class='stat-engines' id='engineStat'>"
            + "Engines: <span class='used' id='usedEngines'>—</span><span style='color:#666'> / <span id='maxEngines'>—</span></span></span>\n"
            + "  <span class='sep'>|</span>\n"
            + "  <span id='uptimeStat'>Uptime: —</span>\n"
            + "  <span class='stat-links'>\n"
            + "    <a class='stat-link' href='#' id='refreshLink'>[Refresh]</a>\n"
            + "  </span>\n"
            + "</div>\n"

            // ── Cap warning (text populated dynamically by updateStats)
            + "<div class='cap-warning hidden' id='capWarning'></div>\n"

            // ── Action cards
            + "<div class='cards'>\n"
            + "  <div class='card' id='spCard'>\n"
            + "    <div class='card-title'>Single Player</div>\n"
            + "    <div class='field'><label>WAD / Game</label>"
            + "<div class='select-wrap' id='spWadWrap'><select id='spWad'></select></div>"
            + "<div class='detect-badge' id='spDetectBadge'>"
            + "<span class='db-icon'>&#9670;</span>Auto-detected:&nbsp;<span class='db-name' id='spDetectName'></span>"
            + "</div></div>\n"
            + "    <div class='field' id='spPwadField' style='display:none'><label>PWAD / Mod</label>"
            + "<div class='select-wrap'><select id='spPwad' onchange='onPwadChange(\"sp\")'><option value=''>\u2014 None \u2014</option></select></div></div>\n"
            + "    <div class='field' id='spSkillField' style='display:none'><label>Skill</label>"
            + "<div class='select-wrap'><select id='spSkill'>"
            + "<option value='0'>1 \u2014 I'm Too Young To Die</option>"
            + "<option value='1'>2 \u2014 Hey, Not Too Rough</option>"
            + "<option value='2' selected>3 \u2014 Hurt Me Plenty</option>"
            + "<option value='3'>4 \u2014 Ultra-Violence</option>"
            + "<option value='4'>5 \u2014 Nightmare!</option>"
            + "</select></div></div>\n"
            + "    <button class='btn' id='spBtn' onclick='startSinglePlayer()'>&#9654; Start Game</button>\n"
            + "  </div>\n"
            + "  <div class='card' id='dmCard'>\n"
            + "    <div class='card-title'>Deathmatch</div>\n"
            + "    <div class='field'><label>WAD / Game</label>"
            + "<div class='select-wrap' id='dmWadWrap'><select id='dmWad' onchange='onDmWadChange()'></select></div>"
            + "<div class='detect-badge' id='dmDetectBadge'>"
            + "<span class='db-icon'>&#9670;</span>Auto-detected:&nbsp;<span class='db-name' id='dmDetectName'></span>"
            + "</div></div>\n"
            + "    <div class='field' id='dmPwadField' style='display:none'><label>PWAD / Mod</label>"
            + "<div class='select-wrap'><select id='dmPwad' onchange='onPwadChange(\"dm\")'><option value=''>\u2014 None \u2014</option></select></div></div>\n"
            + "    <div class='field'><label>Starting Level</label>"
            + "<div class='select-wrap'><select id='dmMap'></select></div></div>\n"
            + "    <div class='field'><label>Number of Players</label>"
            + "<div class='select-wrap'><select id='dmPlayers'>"
            + "<option value='2'>2 Players</option>"
            + "<option value='3'>3 Players</option>"
            + "<option value='4'>4 Players</option>"
            + "</select></div></div>\n"
            + "    <div class='field'><label>Match ID <span style='color:#777;font-size:10px;letter-spacing:1px'>(OPTIONAL)</span></label>"
            + "<input type='text' id='dmMatchId' class='match-id-input' placeholder='e.g. FRAGFEST  \u2014 leave blank to auto-generate' maxlength='12'>"
            + "<div class='match-id-hint'>3\u201312 letters / numbers \u00b7 shared with other players to join</div></div>\n"
            + "    <button class='btn' id='dmBtn' onclick='createMatch()'>&#9760; Create Match</button>\n"
            + "  </div>\n"
            + "</div>\n"

            // ── Active Sessions table
            + "<div class='section-header'>"
            + "<span class='section-title'>Active Sessions</span>"
            + "<span class='section-count' id='sessionCount'></span>"
            + "</div>\n"
            + "<table><thead><tr>"
            + "<th>Session ID</th><th>WAD</th><th>Active</th><th>Status</th>"
            + "</tr></thead><tbody id='sessionTbody'>"
            + "<tr class='empty-row'><td colspan='4'>Loading\u2026</td></tr>"
            + "</tbody></table>\n"

            // ── Active Matches table
            + "<div class='section-header'>"
            + "<span class='section-title'>Active Matches</span>"
            + "<span class='section-count' id='matchCount'></span>"
            + "</div>\n"
            + "<table><thead><tr>"
            + "<th>Match ID</th><th>WAD</th><th>Players</th><th>Active</th><th>Status</th><th>Action</th>"
            + "</tr></thead><tbody id='matchTbody'>"
            + "<tr class='empty-row'><td colspan='6'>Loading\u2026</td></tr>"
            + "</tbody></table>\n"

            // ── Footer
            + "<div class='footer'>"
            + "<span class='footer-note'>IGNITION DOOM &nbsp;&middot;&nbsp; GNU GPL v3</span>"
            + "</div>\n"

            // ── Script
            + "<script>\n"
            + "var WAD_LABELS = {\n"
            + "  'DOOM1':    'DOOM I \\u2014 Shareware (Episode 1)',\n"
            + "  'DOOM':     'DOOM I \\u2014 Ultimate DOOM (Episodes 1\\u20134)',\n"
            + "  'DOOM2':    'DOOM II \\u2014 Hell on Earth',\n"
            + "  'TNT':      'Final DOOM \\u2014 TNT: Evilution',\n"
            + "  'PLUTONIA': 'Final DOOM \\u2014 The Plutonia Experiment'\n"
            + "};\n"
            + "var WAD_ORDER = ['DOOM','DOOM2','PLUTONIA','TNT','DOOM1'];\n"
            + "var WAD_MAPS = {\n"
            + "  'DOOM1':[\n"
            + "    {v:'__random',l:'\u2605 Random'},{v:'__vanilla',l:'  Vanilla'},{v:'__sep',l:'\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500'},\n"
            + "    {v:'1,1',l:'E1M1 \u2014 Hangar'},{v:'1,2',l:'E1M2 \u2014 Nuclear Plant'},{v:'1,3',l:'E1M3 \u2014 Toxin Refinery'},\n"
            + "    {v:'1,4',l:'E1M4 \u2014 Command Control'},{v:'1,5',l:'E1M5 \u2014 Phobos Lab'},{v:'1,6',l:'E1M6 \u2014 Central Processing'},\n"
            + "    {v:'1,7',l:'E1M7 \u2014 Computer Station'},{v:'1,8',l:'E1M8 \u2014 Phobos Anomaly'},{v:'1,9',l:'E1M9 \u2014 Military Base'}\n"
            + "  ],\n"
            + "  'DOOM':[\n"
            + "    {v:'__random',l:'\u2605 Random'},{v:'__vanilla',l:'  Vanilla'},{v:'__sep',l:'\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500'},\n"
            + "    {v:'1,1',l:'E1M1 \u2014 Hangar'},{v:'1,2',l:'E1M2 \u2014 Nuclear Plant'},{v:'1,3',l:'E1M3 \u2014 Toxin Refinery'},\n"
            + "    {v:'1,4',l:'E1M4 \u2014 Command Control'},{v:'1,5',l:'E1M5 \u2014 Phobos Lab'},{v:'1,6',l:'E1M6 \u2014 Central Processing'},\n"
            + "    {v:'1,7',l:'E1M7 \u2014 Computer Station'},{v:'1,8',l:'E1M8 \u2014 Phobos Anomaly'},{v:'1,9',l:'E1M9 \u2014 Military Base'},\n"
            + "    {v:'2,1',l:'E2M1 \u2014 Deimos Anomaly'},{v:'2,2',l:'E2M2 \u2014 Containment Area'},{v:'2,3',l:'E2M3 \u2014 Refinery'},\n"
            + "    {v:'2,4',l:'E2M4 \u2014 Deimos Lab'},{v:'2,5',l:'E2M5 \u2014 Command Center'},{v:'2,6',l:'E2M6 \u2014 Halls of the Damned'},\n"
            + "    {v:'2,7',l:'E2M7 \u2014 Spawning Vats'},{v:'2,8',l:'E2M8 \u2014 Tower of Babel'},{v:'2,9',l:'E2M9 \u2014 Fortress of Mystery'},\n"
            + "    {v:'3,1',l:'E3M1 \u2014 Hell Keep'},{v:'3,2',l:'E3M2 \u2014 Slough of Despair'},{v:'3,3',l:'E3M3 \u2014 Pandemonium'},\n"
            + "    {v:'3,4',l:'E3M4 \u2014 House of Pain'},{v:'3,5',l:'E3M5 \u2014 Unholy Cathedral'},{v:'3,6',l:'E3M6 \u2014 Mt. Erebus'},\n"
            + "    {v:'3,7',l:'E3M7 \u2014 Limbo'},{v:'3,8',l:'E3M8 \u2014 Dis'},{v:'3,9',l:'E3M9 \u2014 Warrens'},\n"
            + "    {v:'4,1',l:'E4M1 \u2014 Hell Beneath'},{v:'4,2',l:'E4M2 \u2014 Perfect Hatred'},{v:'4,3',l:'E4M3 \u2014 Sever the Wicked'},\n"
            + "    {v:'4,4',l:'E4M4 \u2014 Unruly Evil'},{v:'4,5',l:'E4M5 \u2014 They Will Repent'},{v:'4,6',l:'E4M6 \u2014 Against Thee Wickedly'},\n"
            + "    {v:'4,7',l:'E4M7 \u2014 And Hell Followed'},{v:'4,8',l:'E4M8 \u2014 Unto the Cruel'},{v:'4,9',l:'E4M9 \u2014 Fear'}\n"
            + "  ],\n"
            + "  'DOOM2':[\n"
            + "    {v:'__random',l:'\u2605 Random'},{v:'__vanilla',l:'  Vanilla'},{v:'__sep',l:'\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500'},\n"
            + "    {v:'1', l:'MAP01 \u2014 Entryway'},{v:'2', l:'MAP02 \u2014 Underhalls'},{v:'3', l:'MAP03 \u2014 The Gantlet'},\n"
            + "    {v:'4', l:'MAP04 \u2014 The Focus'},{v:'5', l:'MAP05 \u2014 The Waste Tunnels'},{v:'6', l:'MAP06 \u2014 The Crusher'},\n"
            + "    {v:'7', l:'MAP07 \u2014 Dead Simple'},{v:'8', l:'MAP08 \u2014 Tricks and Traps'},{v:'9', l:'MAP09 \u2014 The Pit'},\n"
            + "    {v:'10',l:'MAP10 \u2014 Refueling Base'},{v:'11',l:'MAP11 \u2014 \u2019O\u2019 of Destruction!'},{v:'12',l:'MAP12 \u2014 The Factory'},\n"
            + "    {v:'13',l:'MAP13 \u2014 Downtown'},{v:'14',l:'MAP14 \u2014 The Inmost Dens'},{v:'15',l:'MAP15 \u2014 Industrial Zone'},\n"
            + "    {v:'16',l:'MAP16 \u2014 Suburbs'},{v:'17',l:'MAP17 \u2014 Tenements'},{v:'18',l:'MAP18 \u2014 The Courtyard'},\n"
            + "    {v:'19',l:'MAP19 \u2014 The Citadel'},{v:'20',l:'MAP20 \u2014 Gotcha!'},{v:'21',l:'MAP21 \u2014 Nirvana'},\n"
            + "    {v:'22',l:'MAP22 \u2014 The Catacombs'},{v:'23',l:'MAP23 \u2014 Barrels o\u2019 Fun'},{v:'24',l:'MAP24 \u2014 The Chasm'},\n"
            + "    {v:'25',l:'MAP25 \u2014 Bloodfalls'},{v:'26',l:'MAP26 \u2014 The Abandoned Mines'},{v:'27',l:'MAP27 \u2014 Monster Condo'},\n"
            + "    {v:'28',l:'MAP28 \u2014 The Spirit World'},{v:'29',l:'MAP29 \u2014 The Living End'},{v:'30',l:'MAP30 \u2014 Icon of Sin'},\n"
            + "    {v:'31',l:'MAP31 \u2014 Wolfenstein'},{v:'32',l:'MAP32 \u2014 Grosse'}\n"
            + "  ],\n"
            + "  'TNT':[\n"
            + "    {v:'__random',l:'\u2605 Random'},{v:'__vanilla',l:'  Vanilla'},{v:'__sep',l:'\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500'},\n"
            + "    {v:'1', l:'MAP01 \u2014 System Control'},{v:'2', l:'MAP02 \u2014 Human BBQ'},{v:'3', l:'MAP03 \u2014 Power Control'},\n"
            + "    {v:'4', l:'MAP04 \u2014 Wormhole'},{v:'5', l:'MAP05 \u2014 Hanger'},{v:'6', l:'MAP06 \u2014 Open Season'},\n"
            + "    {v:'7', l:'MAP07 \u2014 Prison'},{v:'8', l:'MAP08 \u2014 Metal'},{v:'9', l:'MAP09 \u2014 Stronghold'},\n"
            + "    {v:'10',l:'MAP10 \u2014 Redemption'},{v:'11',l:'MAP11 \u2014 Storage Facility'},{v:'12',l:'MAP12 \u2014 Crater'},\n"
            + "    {v:'13',l:'MAP13 \u2014 Nukage Processing'},{v:'14',l:'MAP14 \u2014 Steel Works'},{v:'15',l:'MAP15 \u2014 Dead Zone'},\n"
            + "    {v:'16',l:'MAP16 \u2014 Deepest Reaches'},{v:'17',l:'MAP17 \u2014 Processing Area'},{v:'18',l:'MAP18 \u2014 Mill'},\n"
            + "    {v:'19',l:'MAP19 \u2014 Shipping/Respawning'},{v:'20',l:'MAP20 \u2014 Central Processing'},{v:'21',l:'MAP21 \u2014 Administration Center'},\n"
            + "    {v:'22',l:'MAP22 \u2014 Habitat'},{v:'23',l:'MAP23 \u2014 Lunar Mining Project'},{v:'24',l:'MAP24 \u2014 Quarry'},\n"
            + "    {v:'25',l:'MAP25 \u2014 Baron\u2019s Den'},{v:'26',l:'MAP26 \u2014 Ballistyx'},{v:'27',l:'MAP27 \u2014 Mount Pain'},\n"
            + "    {v:'28',l:'MAP28 \u2014 Heck'},{v:'29',l:'MAP29 \u2014 River Styx'},{v:'30',l:'MAP30 \u2014 Last Call'},\n"
            + "    {v:'31',l:'MAP31 \u2014 Pharaoh'},{v:'32',l:'MAP32 \u2014 Caribbean'}\n"
            + "  ],\n"
            + "  'PLUTONIA':[\n"
            + "    {v:'__random',l:'\u2605 Random'},{v:'__vanilla',l:'  Vanilla'},{v:'__sep',l:'\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500'},\n"
            + "    {v:'1', l:'MAP01 \u2014 Congo'},{v:'2', l:'MAP02 \u2014 Well of Souls'},{v:'3', l:'MAP03 \u2014 Aztec'},\n"
            + "    {v:'4', l:'MAP04 \u2014 Caged'},{v:'5', l:'MAP05 \u2014 Ghost Town'},{v:'6', l:'MAP06 \u2014 Baron\u2019s Lair'},\n"
            + "    {v:'7', l:'MAP07 \u2014 Caughtyard'},{v:'8', l:'MAP08 \u2014 Realm'},{v:'9', l:'MAP09 \u2014 Abattoire'},\n"
            + "    {v:'10',l:'MAP10 \u2014 Onslaught'},{v:'11',l:'MAP11 \u2014 Hunted'},{v:'12',l:'MAP12 \u2014 Speed'},\n"
            + "    {v:'13',l:'MAP13 \u2014 The Crypt'},{v:'14',l:'MAP14 \u2014 Genesis'},{v:'15',l:'MAP15 \u2014 The Twilight'},\n"
            + "    {v:'16',l:'MAP16 \u2014 The Omen'},{v:'17',l:'MAP17 \u2014 Compound'},{v:'18',l:'MAP18 \u2014 Neurosphere'},\n"
            + "    {v:'19',l:'MAP19 \u2014 NME'},{v:'20',l:'MAP20 \u2014 The Death Domain'},{v:'21',l:'MAP21 \u2014 Slayer'},\n"
            + "    {v:'22',l:'MAP22 \u2014 Impossible Mission'},{v:'23',l:'MAP23 \u2014 Tombstone'},{v:'24',l:'MAP24 \u2014 The Final Frontier'},\n"
            + "    {v:'25',l:'MAP25 \u2014 The Temple of Darkness'},{v:'26',l:'MAP26 \u2014 Bunker'},{v:'27',l:'MAP27 \u2014 Anti-Christ'},\n"
            + "    {v:'28',l:'MAP28 \u2014 The Sewers'},{v:'29',l:'MAP29 \u2014 Odyssey of Noises'},{v:'30',l:'MAP30 \u2014 The Gateway of Hell'},\n"
            + "    {v:'31',l:'MAP31 \u2014 Cyberden'},{v:'32',l:'MAP32 \u2014 Go 2 It'}\n"
            + "  ]\n"
            + "};\n"
            + "function populateDmMaps(wad) {\n"
            + "  var maps=WAD_MAPS[wad]||WAD_MAPS['DOOM2'];\n"
            + "  var sel=document.getElementById('dmMap'); if(!sel) return;\n"
            + "  var prev=sel.value; sel.innerHTML='';\n"
            + "  maps.forEach(function(m){\n"
            + "    var opt=document.createElement('option');\n"
            + "    opt.value=m.v; opt.textContent=m.l;\n"
            + "    if(m.v==='__sep') opt.disabled=true;\n"
            + "    sel.appendChild(opt);\n"
            + "  });\n"
            + "  if(prev&&prev.charAt(0)!=='_'){\n"
            + "    for(var i=0;i<sel.options.length;i++){if(sel.options[i].value===prev){sel.value=prev;break;}}\n"
            + "  }\n"
            + "}\n"
            + "function onDmWadChange(){populateDmMaps(document.getElementById('dmWad').value);}\n"
            + "function firstMapToWarp(m){\n"
            + "  var em=/^E(\\d)M(\\d)$/i.exec(m); if(em) return em[1]+','+em[2];\n"
            + "  var mp=/^MAP(\\d+)$/i.exec(m); if(mp) return String(parseInt(mp[1],10));\n"
            + "  return '';\n"
            + "}\n"

            // Branding: hide the separator if both logos are missing
            + "var _brandFailed = 0;\n"
            + "function checkBrandingEmpty() {\n"
            + "  _brandFailed++;\n"
            + "  if (_brandFailed >= " + brandTotal + ") document.getElementById('brandingRow').style.display='none';\n"
            + "}\n"

            + "function fmtMs(ms) {\n"
            + "  var s=Math.floor(ms/1000), m=Math.floor(s/60); s=s%60;\n"
            + "  var h=Math.floor(m/60); m=m%60;\n"
            + "  if(h>0) return h+'h '+pad(m)+'m';\n"
            + "  if(m>0) return m+'m '+pad(s)+'s';\n"
            + "  return s+'s';\n"
            + "}\n"
            + "function fmtUptime(sec) {\n"
            + "  var m=Math.floor(sec/60), h=Math.floor(m/60); m=m%60;\n"
            + "  if(h>0) return h+'h '+pad(m)+'m';\n"
            + "  return m+'m '+Math.floor(sec%60)+'s';\n"
            + "}\n"
            + "function pad(n){ return n<10?'0'+n:''+n; }\n"
            + "function esc(s){ return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;'); }\n"

            + "function copyId(el, id) {\n"
            + "  navigator.clipboard.writeText(id).catch(function(){});\n"
            + "  var f=el.querySelector('.copied-flash');\n"
            + "  if(!f) return;\n"
            + "  f.classList.add('show');\n"
            + "  setTimeout(function(){ f.classList.remove('show'); }, 1400);\n"
            + "}\n"

            + "function populateWads(wads) {\n"
            + "  var stems=wads.map(function(w){return w.replace(/\\.wad$/i,'').toUpperCase();});\n"
            + "  stems.sort(function(a,b){\n"
            + "    var ai=WAD_ORDER.indexOf(a), bi=WAD_ORDER.indexOf(b);\n"
            + "    if(ai<0&&bi<0) return a.localeCompare(b);\n"
            + "    if(ai<0) return 1;\n"
            + "    if(bi<0) return -1;\n"
            + "    return ai-bi;\n"
            + "  });\n"
            + "  ['spWad','dmWad'].forEach(function(id) {\n"
            + "    var sel=document.getElementById(id), prev=sel.value;\n"
            + "    sel.innerHTML='';\n"
            + "    stems.forEach(function(stem) {\n"
            + "      var opt=document.createElement('option');\n"
            + "      opt.value=stem;\n"
            + "      opt.textContent=WAD_LABELS[stem]||stem;\n"
            + "      sel.appendChild(opt);\n"
            + "    });\n"
            + "    if(stems.indexOf(prev)>=0) sel.value=prev;\n"
            + "  });\n"
            + "  onDmWadChange();\n"
            + "}\n"
            + "var pwadMeta={};\n"
            + "function populatePwads(pwads) {\n"
            + "  pwadMeta={};\n"
            + "  var names=[];\n"
            + "  pwads.forEach(function(p) {\n"
            + "    var name=typeof p==='string'?p:p.name;\n"
            + "    names.push(name);\n"
            + "    if(typeof p==='object') pwadMeta[name]=p;\n"
            + "  });\n"
            + "  ['spPwad','dmPwad'].forEach(function(id) {\n"
            + "    var sel=document.getElementById(id), prev=sel.value;\n"
            + "    sel.innerHTML='<option value=\"\">\u2014 None \u2014</option>';\n"
            + "    names.forEach(function(n) {\n"
            + "      var opt=document.createElement('option');\n"
            + "      opt.value=n; opt.textContent=n;\n"
            + "      sel.appendChild(opt);\n"
            + "    });\n"
            + "    if(prev && names.indexOf(prev)>=0) sel.value=prev;\n"
            + "  });\n"
            + "  var show=names.length>0;\n"
            + "  document.getElementById('spPwadField').style.display=show?'':'none';\n"
            + "  document.getElementById('dmPwadField').style.display=show?'':'none';\n"
            + "  if(!show) { document.getElementById('spSkillField').style.display='none'; }\n"
            + "  onPwadChange('sp'); onPwadChange('dm');\n"
            + "}\n"
            + "function onPwadChange(prefix) {\n"
            + "  var sel=document.getElementById(prefix+'Pwad');\n"
            + "  var name=sel?sel.value:'';\n"
            + "  var meta=name?pwadMeta[name]:null;\n"
            + "  var badge=document.getElementById(prefix+'DetectBadge');\n"
            + "  var nameEl=document.getElementById(prefix+'DetectName');\n"
            + "  if(prefix==='sp') document.getElementById('spSkillField').style.display=name?'':'none';\n"
            + "  if(!meta||!meta.iwad){if(badge)badge.className='detect-badge';if(prefix==='dm')onDmWadChange();return;}\n"
            + "  var wadSel=document.getElementById(prefix+'Wad');\n"
            + "  var matched=false;\n"
            + "  for(var i=0;i<wadSel.options.length;i++){\n"
            + "    if(wadSel.options[i].value.toUpperCase()===meta.iwad.toUpperCase()){\n"
            + "      wadSel.value=wadSel.options[i].value; matched=true; break;\n"
            + "    }\n"
            + "  }\n"
            + "  if(matched){\n"
            + "    var wrap=document.getElementById(prefix+'WadWrap');\n"
            + "    if(wrap){wrap.classList.remove('wad-flash');void wrap.offsetWidth;wrap.classList.add('wad-flash');}\n"
            + "  }\n"
            + "  if(badge){badge.className='detect-badge'+(matched?'':' unavailable')+' visible';}\n"
            + "  if(nameEl){nameEl.textContent=meta.iwad+(matched?'':' \u2014 not available');}\n"
            + "  if(prefix==='dm'){\n"
            + "    populateDmMaps(matched?meta.iwad:document.getElementById('dmWad').value);\n"
            + "    if(meta.firstMap){\n"
            + "      var wv=firstMapToWarp(meta.firstMap);\n"
            + "      var ms=document.getElementById('dmMap');\n"
            + "      if(wv&&ms){for(var j=0;j<ms.options.length;j++){if(ms.options[j].value===wv){ms.value=wv;break;}}}\n"
            + "    }\n"
            + "  }\n"
            + "}\n"

            + "function renderSessions(sessions) {\n"
            + "  var tbody=document.getElementById('sessionTbody');\n"
            + "  var n=sessions.length;\n"
            + "  document.getElementById('sessionCount').textContent=n===0?'none active':n===1?'1 active':n+' active';\n"
            + "  if(n===0){ tbody.innerHTML=\"<tr class='empty-row'><td colspan='4'>No active sessions</td></tr>\"; return; }\n"
            + "  tbody.innerHTML=sessions.map(function(s){\n"
            + "    return \"<tr>\"\n"
            + "      +\"<td class='cell-id' onclick='copyId(this,\\\"\"+esc(s.id)+\"\\\")' title='Click to copy'>\"+esc(s.id)+\"<span class='copied-flash'>Copied!</span></td>\"\n"
            + "      +\"<td class='cell-wad'>\"+esc(s.wad||'\\u2014')+\"</td>\"\n"
            + "      +\"<td class='cell-time'>\"+fmtMs(s.uptimeMs)+\"</td>\"\n"
            + "      +\"<td><span class='cell-status-running'>&#9679; Running</span></td>\"\n"
            + "      +\"</tr>\";\n"
            + "  }).join('');\n"
            + "}\n"

            + "function renderMatches(matches) {\n"
            + "  var tbody=document.getElementById('matchTbody');\n"
            + "  var n=matches.length;\n"
            + "  document.getElementById('matchCount').textContent=n===0?'none active':n===1?'1 active':n+' active';\n"
            + "  if(n===0){ tbody.innerHTML=\"<tr class='empty-row'><td colspan='6'>No active matches</td></tr>\"; return; }\n"
            + "  tbody.innerHTML=matches.map(function(m){\n"
            + "    var isFull=(m.joined>=m.players)||m.running;\n"
            + "    var joinUrl='/system/doom/match/join?match='+encodeURIComponent(m.id)+'&wad='+encodeURIComponent(m.wad||'')+(_playToken?'&auth='+encodeURIComponent(_playToken):'');\n"
            + "    var statusEl=m.running?\"<span class='cell-status-running'>&#9679; Running</span>\":\"<span class='cell-status-lobby'>&#9675; Lobby</span>\";\n"
            + "    var joinEl=isFull?\"<a class='join-link full'>Full</a>\":\"<a class='join-link' href='\"+joinUrl+\"' target='_blank'>Join</a>\";\n"
            + "    var pJoined=isFull?\"<span class='joined'>\"+m.joined+\"</span>\":\"<span class='waiting'>\"+m.joined+\"</span>\";\n"
            + "    return \"<tr>\"\n"
            + "      +\"<td class='cell-id' onclick='copyId(this,\\\"\"+esc(m.id)+\"\\\")' title='Click to copy'>\"+esc(m.id)+\"<span class='copied-flash'>Copied!</span></td>\"\n"
            + "      +\"<td class='cell-wad'>\"+esc(m.wad||'\\u2014')+\"</td>\"\n"
            + "      +\"<td class='cell-players'>\"+pJoined+\" / \"+m.players+\"</td>\"\n"
            + "      +\"<td class='cell-time'>\"+fmtMs(m.uptimeMs)+\"</td>\"\n"
            + "      +\"<td>\"+statusEl+\"</td>\"\n"
            + "      +\"<td>\"+joinEl+\"</td>\"\n"
            + "      +\"</tr>\";\n"
            + "  }).join('');\n"
            + "}\n"

            + "function updateStats(h) {\n"
            + "  var used=h.activeSessions, cap=h.maxSessions, full=used>=cap;\n"
            + "  document.getElementById('usedEngines').textContent=used;\n"
            + "  document.getElementById('maxEngines').textContent=cap;\n"
            + "  document.getElementById('engineStat').className='stat-engines'+(full?' full':'');\n"
            + "  document.getElementById('uptimeStat').textContent='Uptime: '+fmtUptime(h.uptimeSeconds);\n"
            + "  var warn=document.getElementById('capWarning');\n"
            + "  if(full){warn.textContent='\u26A0 All engine slots are in use ('+used+' / '+cap+'). Stop an existing session before starting a new one.';warn.className='cap-warning';}\n"
            + "  else{warn.className='cap-warning hidden';}\n"
            + "}\n"

            + "function apply(h) {\n"
            + "  populateWads(h.availableWads||[]);\n"
            + "  populatePwads(h.availablePwads||[]);\n"
            + "  renderSessions(h.sessions||[]);\n"
            + "  renderMatches(h.matches||[]);\n"
            + "  updateStats(h);\n"
            + "}\n"

            + "function refresh() {\n"
            + "  fetch('/system/doom/health')\n"
            + "    .then(function(r){ return r.json(); })\n"
            + "    .then(apply)\n"
            + "    .catch(function(e){ console.warn('Health fetch failed:', e); });\n"
            + "}\n"

            + "function startSinglePlayer() {\n"
            + "  var wad=document.getElementById('spWad').value;\n"
            + "  var pwad=document.getElementById('spPwad').value;\n"
            + "  var skill=document.getElementById('spSkill').value;\n"
            + "  var url='/system/doom/play?wad='+encodeURIComponent(wad)+'&skill='+skill;\n"
            + "  if(pwad) url+='&pwad='+encodeURIComponent(pwad);\n"
            + "  if(_playToken) url+='&auth='+encodeURIComponent(_playToken);\n"
            + "  window.open(url,'_blank');\n"
            + "}\n"
            + "function createMatch() {\n"
            + "  var wad=document.getElementById('dmWad').value;\n"
            + "  var players=document.getElementById('dmPlayers').value;\n"
            + "  var pwad=document.getElementById('dmPwad').value;\n"
            + "  var matchId=document.getElementById('dmMatchId').value.trim().toUpperCase().replace(/[^A-Z0-9\\-]/g,'');\n"
            + "  var mapVal=document.getElementById('dmMap').value;\n"
            + "  if(mapVal==='__random'){\n"
            + "    var pool=(WAD_MAPS[wad]||[]).filter(function(m){return m.v.charAt(0)!=='_';});\n"
            + "    mapVal=pool.length>0?pool[Math.floor(Math.random()*pool.length)].v:'';\n"
            + "  } else if(mapVal==='__vanilla'){mapVal='';}\n"
            + "  var url='/system/doom/match/create?wad='+encodeURIComponent(wad)+'&players='+players;\n"
            + "  if(mapVal) url+='&warp='+encodeURIComponent(mapVal);\n"
            + "  if(pwad) url+='&pwad='+encodeURIComponent(pwad);\n"
            + "  if(matchId) url+='&matchId='+encodeURIComponent(matchId);\n"
            + "  if(_playToken) url+='&auth='+encodeURIComponent(_playToken);\n"
            + "  window.open(url,'_blank');\n"
            + "}\n"

            // ── Auth overlay ────────────────────────────────────────────────────
            + "var _playToken=sessionStorage.getItem('doomPlayToken');\n"
            + "function showAuthOverlay(){\n"
            + "  document.getElementById('authOverlay').classList.add('visible');\n"
            + "  setTimeout(function(){ document.getElementById('authPw').focus(); },50);\n"
            + "}\n"
            + "function submitAuth(){\n"
            + "  var pw=document.getElementById('authPw').value;\n"
            + "  document.getElementById('authErr').textContent='';\n"
            + "  fetch('/system/doom/auth',{method:'POST',headers:{'Content-Type':'text/plain'},body:pw})\n"
            + "    .then(function(r){ if(r.ok) return r.json(); throw new Error(); })\n"
            + "    .then(function(d){\n"
            + "      _playToken=d.token;\n"
            + "      sessionStorage.setItem('doomPlayToken',_playToken);\n"
            + "      document.getElementById('authOverlay').classList.remove('visible');\n"
            + "      document.getElementById('authPw').value='';\n"
            + "    })\n"
            + "    .catch(function(){ document.getElementById('authErr').textContent='Incorrect password.'; document.getElementById('authPw').select(); });\n"
            + "}\n"
            + "if(!_playToken) showAuthOverlay();\n"
            + "\n"
            + "document.getElementById('refreshLink').addEventListener('click',function(e){ e.preventDefault(); refresh(); });\n"
            + "refresh();\n"
            + "setInterval(refresh, 10000);\n"
            + "</script>\n"
            + "</body></html>\n";
    }
}
