/*
 * Copyright (C) 2026 Mike Dillmann (DivCurl)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.doom.gateway;

/**
 * Serves a complete standalone DOOM player page.
 *
 * Session-aware: the server injects SESSION_ID and WAD_NAME into the page HTML;
 * all browser fetch calls append ?session=SESSION_ID so the servlet can route to the correct
 * DoomSession. The session ID is also stored in sessionStorage so page refreshes reuse the
 * same session (as long as the tab isn't closed and the session hasn't been reaped).
 *
 * Transport: WebSocket (/doom-ws) is the primary channel for input and audio events.
 * Falls back to POST /input + SSE /events/stream if WebSocket is unavailable.
 */
public class DoomPlayPage {

    /**
     * Returns the full HTML page for a DOOM player session.
     *
     * @param sessionId Server-assigned session UUID (injected into JS as SESSION_ID constant).
     * @param wadName   WAD name stem used by this session (e.g. "DOOM1", "DOOM2").
     */
    public static String getHTML(String sessionId, String wadName) {
        // Escape for safe embedding in a JS string literal
        String safeSession = sessionId.replace("'", "\\'");
        String safeWad     = wadName.replace("'", "\\'");

        return "<!DOCTYPE html>\n"
            + "<html><head>\n"
            + "<meta charset='UTF-8'>\n"
            + "<title>DOOM on Ignition - " + escapeHtml(wadName) + "</title>\n"
            + "<style>\n"
            + "* { margin:0; padding:0; box-sizing:border-box; }\n"
            + "html, body { width:100%; height:100%; overflow:hidden; }\n"
            + "body {\n"
            + "  background:#1a1a1a; color:#fff;\n"
            + "  font-family:monospace; font-size:14px;\n"
            + "  display:flex; flex-direction:column;\n"
            + "}\n"
            + "#controls {\n"
            + "  flex-shrink:0;\n"
            + "  text-align:center; padding:8px 15px;\n"
            + "  background:#222;\n"
            + "}\n"
            + "#game-container {\n"
            + "  flex:1; min-height:0;\n"
            + "  background:#000;\n"
            + "  position:relative;\n"
            + "  outline:none;\n"
            + "}\n"
            + "#game-container:focus {\n"
            + "  outline: 3px solid #c0392b;\n"
            + "  cursor: none;\n"
            + "}\n"
            + "#frame {\n"
            + "  width:100%; height:100%;\n"
            + "  object-fit:contain;\n"
            + "  object-position:center;\n"
            + "  image-rendering:pixelated;\n"
            + "  image-rendering:-moz-crisp-edges;\n"
            + "  image-rendering:crisp-edges;\n"
            + "}\n"
            + "#status {\n"
            + "  flex-shrink:0;\n"
            + "  padding:4px; font-size:12px; color:#888;\n"
            + "  text-align:center; background:#1a1a1a;\n"
            + "}\n"
            + ".stat { display:inline-block; margin:0 10px; }\n"
            + "#latency { display:inline-block; min-width:4ch; text-align:right; }\n"
            + "#doomConsole {\n"
            + "  display:none; position:fixed; bottom:0; left:0; right:0;\n"
            + "  background:rgba(0,0,0,0.88); color:#00ff00; font:14px monospace;\n"
            + "  padding:8px 12px; z-index:9999; border-top:2px solid #00ff00;\n"
            + "}\n"
            + "#consoleOut { max-height:110px; overflow-y:auto; margin-bottom:4px; font-size:12px; line-height:1.4; }\n"
            + ".con-row { display:flex; align-items:center; gap:6px; }\n"
            + "#consoleIn { flex:1; background:transparent; border:none; outline:none;\n"
            + "  color:#00ff00; font:14px monospace; caret-color:#00ff00; width:100%; }\n"
            + "</style>\n"
            + "</head><body>\n"
            + "<div id='controls'>\n"
            + "  <strong style='color:#c0392b'>Controls:</strong> Arrow Keys = Move/Turn | Ctrl = Fire | Space = Use/Open | Esc = Menu | ~ = Console<br>\n"
            + "  <small style='color:#888'><span style='color:#ddd'>" + escapeHtml(wadName) + "</span>"
            + " | Session: <span id='sid' title='Click to copy' style='cursor:pointer;text-decoration:underline dotted'>"
            + sessionId + "</span></small>\n"
            + "</div>\n"
            + "<div id='game-container' tabindex='0'>\n"
            + "  <img id='frame' alt='DOOM Frame'/>\n"
            + "</div>\n"
            + "<div id='status'>\n"
            + "  <span class='stat'>Latency: <span id='latency'>--</span>ms</span>\n"
            + "</div>\n"
            + "<div id='doomConsole'>\n"
            + "  <div id='consoleOut'></div>\n"
            + "  <div class='con-row'><span>&gt;</span>\n"
            + "    <input id='consoleIn' type='text' autocomplete='off'\n"
            + "      placeholder='warp 1 1 | map e1m3 | skill 4 | god | noclip | give all | help'/>\n"
            + "  </div>\n"
            + "</div>\n"
            + "<script>\n"
            // ── Session identity (server-injected) ──────────────────────────────
            + "var SESSION_ID = '" + safeSession + "';\n"
            + "var WAD_NAME   = '" + safeWad + "';\n"
            + "sessionStorage.setItem('doomSessionId', SESSION_ID);\n"
            + "(function(){ var a=new URLSearchParams(location.search).get('auth'); if(a) sessionStorage.setItem('doomPlayToken',a); })();\n"
            + "\n"
            + "var container  = document.getElementById('game-container');\n"
            + "var frameImg   = document.getElementById('frame');\n"
            + "var latencyEl  = document.getElementById('latency');\n"
            + "\n"
            // ── Input state tracking ────────────────────────────────────────────
            + "var pressed = {};\n"
            + "\n"
            // ── Console overlay ─────────────────────────────────────────────────
            + "var _consoleOpen = false;\n"
            + "\n"
            + "function _consoleToggle() {\n"
            + "  _consoleOpen = !_consoleOpen;\n"
            + "  document.getElementById('doomConsole').style.display = _consoleOpen ? 'block' : 'none';\n"
            + "  if (_consoleOpen) {\n"
            + "    pressed = {}; sendState();\n"
            + "    document.getElementById('consoleIn').focus();\n"
            + "  } else {\n"
            + "    container.focus();\n"
            + "  }\n"
            + "}\n"
            + "\n"
            + "function _consoleLog(prompt, msg) {\n"
            + "  var out = document.getElementById('consoleOut');\n"
            + "  out.innerHTML += '<div><span style=\"color:#aaa\">&gt; ' + prompt + '</span></div>';\n"
            + "  if (msg) out.innerHTML += '<div>' + msg + '</div>';\n"
            + "  out.scrollTop = out.scrollHeight;\n"
            + "}\n"
            + "\n"
            + "function _consoleExec(cmd) {\n"
            + "  return fetch('/system/doom/console?session=' + SESSION_ID, {\n"
            + "    method: 'POST',\n"
            + "    headers: {'Content-Type': 'application/x-www-form-urlencoded'},\n"
            + "    body: 'command=' + encodeURIComponent(cmd)\n"
            + "  }).then(function(r) { return r.json(); });\n"
            + "}\n"
            + "\n"
            + "document.getElementById('consoleIn').addEventListener('keydown', function(e) {\n"
            + "  e.stopPropagation();\n"
            + "  if (e.key === 'Escape') { _consoleToggle(); return; }\n"
            + "  if (e.key !== 'Enter') return;\n"
            + "  var cmd = this.value.trim();\n"
            + "  this.value = '';\n"
            + "  if (!cmd) { _consoleToggle(); return; }\n"
            + "  _consoleExec(cmd).then(function(r) {\n"
            + "    _consoleLog(cmd, r.message);\n"
            + "  }).catch(function() {\n"
            + "    _consoleLog(cmd, 'Error: server unreachable');\n"
            + "  });\n"
            + "});\n"
            + "\n"
            // ── Game ended overlay ──────────────────────────────────────────────
            + "var gameEnded = false;\n"
            + "var _evtSource = null, _ws = null, _wsOk = false;\n"
            + "function showGameEnded() {\n"
            + "  gameEnded = true;\n"
            + "  if (_evtSource) { _evtSource.close(); _evtSource = null; }\n"
            + "  if (_ws) { _ws.close(); _ws = null; }\n"
            + "  if (typeof _stopAll === 'function') _stopAll();\n"
            + "  var ov = document.createElement('div');\n"
            + "  ov.style.cssText = 'position:fixed;inset:0;background:#000;color:#c00;display:flex;flex-direction:column;align-items:center;justify-content:center;font:bold 28px monospace;z-index:999';\n"
            + "  ov.innerHTML = '<div>GAME ENDED</div><div style=\"font-size:14px;color:#888;margin-top:16px\">You may close this browser tab.</div>';\n"
            + "  document.body.appendChild(ov);\n"
            + "}\n"
            + "\n"
            // ── MJPEG push stream ────────────────────────────────────────────────
            + "frameImg.onload = function() {};\n"
            + "frameImg.onerror = function() {\n"
            + "  if (!gameEnded) {\n"
            + "    fetch('/system/doom/frame?session=' + SESSION_ID)\n"
            + "      .then(function(r) { if (r.status === 410) showGameEnded(); })\n"
            + "      .catch(function() {});\n"
            + "  }\n"
            + "};\n"
            + "\n"
            // ── Input: WebSocket preferred, POST fallback ────────────────────────
            + "function sendState() {\n"
            + "  if (gameEnded) return;\n"
            + "  if (_ws && _ws.readyState === 1) { _ws.send(Object.keys(pressed).join(',')); return; }\n"
            + "  fetch('/system/doom/input?session=' + SESSION_ID, {\n"
            + "    method:'POST', headers:{'Content-Type':'text/plain'},\n"
            + "    body: Object.keys(pressed).join(',')\n"
            + "  }).catch(function(){});\n"
            + "}\n"
            + "\n"
            // ── Keyboard events ─────────────────────────────────────────────────
            + "container.addEventListener('keydown', function(e) {\n"
            + "  if (e.key === '`' || e.keyCode === 192) {\n"
            + "    e.preventDefault(); _consoleToggle(); return;\n"
            + "  }\n"
            + "  if (_consoleOpen) return;\n"
            + "  e.preventDefault(); e.stopPropagation();\n"
            + "  if (!pressed[e.keyCode]) { pressed[e.keyCode] = true; sendState(); }\n"
            + "});\n"
            + "\n"
            + "container.addEventListener('keyup', function(e) {\n"
            + "  e.preventDefault(); e.stopPropagation();\n"
            + "  if (pressed[e.keyCode]) { delete pressed[e.keyCode]; sendState(); }\n"
            + "});\n"
            + "\n"
            + "container.addEventListener('blur', function() { pressed = {}; sendState(); });\n"
            + "window.addEventListener('blur', function() { pressed = {}; sendState(); });\n"
            + "\n"
            // ── SSE: sound + music + latency events ─────────────────────────────
            + "function _openEvents() {\n"
            + "  if (gameEnded) return;\n"
            + "  _evtSource = new EventSource('/system/doom/events/stream?session=' + SESSION_ID);\n"
            + "  _evtSource.addEventListener('sound', function(e) {\n"
            + "    if (!audioContext) return;\n"
            + "    JSON.parse(e.data).forEach(function(ev) { playSound(ev.name,ev.volume,ev.separation,ev.pitch); });\n"
            + "  });\n"
            + "  _evtSource.addEventListener('music', function(e) {\n"
            + "    var s = JSON.parse(e.data);\n"
            + "    _sfVolume = (s.volume !== undefined) ? s.volume / 127 : 1.0;\n"
            + "    if (s.playing && s.changed) {\n"
            + "      fetch('/system/doom/music/midi?session=' + SESSION_ID)\n"
            + "        .then(function(r) { return r.arrayBuffer(); })\n"
            + "        .then(function(buf) { startMidiPlayback(buf, s.looping); })\n"
            + "        .catch(function(e) { console.warn('[Music] MIDI fetch failed:', e); });\n"
            + "    } else if (!s.playing) { _stopAll(); }\n"
            + "  });\n"
            + "  _evtSource.addEventListener('ping', function(e) {\n"
            + "    var ms = Date.now() - parseInt(e.data);\n"
            + "    latencyEl.textContent = ms;\n"
            + "    latencyEl.style.color = ms<50?'#4db87a':ms<150?'#c88a00':'#c0392b';\n"
            + "  });\n"
            + "  _evtSource.onerror = function() { if (!gameEnded) { _evtSource.close(); _evtSource = null; setTimeout(_openEvents, 1000); } };\n"
            + "}\n"
            + "\n"
            // ── WebSocket: bidirectional input + audio (with SSE fallback) ───────
            + "function _connectWS() {\n"
            + "  if (gameEnded) return;\n"
            + "  var _wsTimer = setTimeout(function() { if (_ws && _ws.readyState === 0) _ws.close(); }, 2000);\n"
            + "  var proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
            + "  _ws = new WebSocket(proto + '//' + location.host + '/system/doom-ws?session=' + SESSION_ID);\n"
            + "  _ws.onopen = function() {\n"
            + "    clearTimeout(_wsTimer); _wsOk = true;\n"
            + "    console.log('[DOOM] WS connected — using WebSocket transport');\n"
            + "    if (_evtSource) { _evtSource.onerror = null; _evtSource.close(); _evtSource = null; }\n"
            + "  };\n"
            + "  _ws.onmessage = function(e) {\n"
            + "    var d = e.data;\n"
            + "    if (d.startsWith('pong:')) {\n"
            + "      var ms = Date.now() - parseInt(d.substring(5));\n"
            + "      latencyEl.textContent = ms;\n"
            + "      latencyEl.style.color = ms<50?'#4db87a':ms<150?'#c88a00':'#c0392b';\n"
            + "    } else if (d.startsWith('sound:')) {\n"
            + "      if (audioContext) JSON.parse(d.substring(6)).forEach(function(ev) { playSound(ev.name,ev.volume,ev.separation,ev.pitch); });\n"
            + "    } else if (d.startsWith('music:')) {\n"
            + "      var s = JSON.parse(d.substring(6));\n"
            + "      _sfVolume = (s.volume !== undefined) ? s.volume / 127 : 1.0;\n"
            + "      if (s.playing && s.changed) {\n"
            + "        fetch('/system/doom/music/midi?session=' + SESSION_ID)\n"
            + "          .then(function(r) { return r.arrayBuffer(); })\n"
            + "          .then(function(buf) { startMidiPlayback(buf, s.looping); })\n"
            + "          .catch(function(e) { console.warn('[Music] MIDI fetch failed:', e); });\n"
            + "      } else if (!s.playing) { _stopAll(); }\n"
            + "    }\n"
            + "  };\n"
            + "  _ws.onclose = function() {\n"
            + "    clearTimeout(_wsTimer); _ws = null;\n"
            + "    if (!gameEnded) {\n"
            + "      if (_wsOk) { _wsOk = false; console.log('[DOOM] WS dropped — reconnecting...'); setTimeout(_connectWS, 1000); }\n"
            + "      else { console.warn('[DOOM] WS unavailable — falling back to SSE+POST'); if (!_evtSource) { _openEvents(); } }\n"
            + "    }\n"
            + "  };\n"
            + "  _ws.onerror = function() {};\n"
            + "}\n"
            + "setInterval(function() { if (_ws && _ws.readyState === 1) _ws.send('ping:' + Date.now()); }, 2000);\n"
            + "_connectWS();\n"
            + "\n"
            // ── Web Audio API sound system ───────────────────────────────────────
            + "var audioContext = null;\n"
            + "var soundBuffers = {};\n"
            + "var soundsLoaded = false;\n"
            + "\n"
            + "function initAudio() {\n"
            + "  try {\n"
            + "    audioContext = new (window.AudioContext || window.webkitAudioContext)();\n"
            + "    _masterGain = audioContext.createGain(); _masterGain.gain.value = 0.9;\n"
            + "    var _eq1 = audioContext.createBiquadFilter();\n"
            + "    _eq1.type = 'lowshelf'; _eq1.frequency.value = 100; _eq1.gain.value = 4;\n"
            + "    var _eq2 = audioContext.createBiquadFilter();\n"
            + "    _eq2.type = 'peaking'; _eq2.frequency.value = 900; _eq2.Q.value = 2; _eq2.gain.value = -3;\n"
            + "    var _eq3 = audioContext.createBiquadFilter();\n"
            + "    _eq3.type = 'highshelf'; _eq3.frequency.value = 5500; _eq3.gain.value = -2;\n"
            + "    _masterGain.connect(_eq1); _eq1.connect(_eq2); _eq2.connect(_eq3); _eq3.connect(audioContext.destination);\n"
            + "    loadSounds();\n"
            + "    initMusicSystem();\n"
            + "  } catch(e) { console.error('Web Audio API error:', e); }\n"
            + "}\n"
            + "\n"
            + "var _soundLoadAttempts = 0;\n"
            + "function loadSounds() {\n"
            + "  fetch('/system/doom/sounds?session=' + SESSION_ID)\n"
            + "    .then(function(r) { return r.json(); })\n"
            + "    .then(function(names) {\n"
            + "      if (names.length === 0) {\n"
            + "        if (++_soundLoadAttempts < 10) {\n"
            + "          setTimeout(loadSounds, 3000);\n"
            + "        } else { console.warn('Sound cache never became ready after 10 attempts'); }\n"
            + "        return;\n"
            + "      }\n"
            + "      var n = names.length, done = 0;\n"
            + "      names.forEach(function(name) {\n"
            + "        fetch('/system/doom/sounds/' + name + '?session=' + SESSION_ID)\n"
            + "          .then(function(r) { return r.arrayBuffer(); })\n"
            + "          .then(function(buf) { return audioContext.decodeAudioData(buf); })\n"
            + "          .then(function(ab) { soundBuffers[name] = ab; if (++done === n) soundsLoaded = true; })\n"
            + "          .catch(function(e) { console.error('Sound load fail:', name, e); });\n"
            + "      });\n"
            + "    })\n"
            + "    .catch(function(e) { console.error('Sound list fail:', e); });\n"
            + "}\n"
            + "\n"
            + "function playSound(name, volume, separation, pitch) {\n"
            + "  if (!audioContext || !soundsLoaded) return;\n"
            + "  var buf = soundBuffers[name]; if (!buf) return;\n"
            + "  try {\n"
            + "    var src = audioContext.createBufferSource();\n"
            + "    src.buffer = buf;\n"
            + "    src.playbackRate.value = pitch / 128.0;\n"
            + "    var gn = audioContext.createGain();\n"
            + "    gn.gain.value = Math.min(1.0, volume / 127.0);\n"
            + "    var pan = audioContext.createStereoPanner();\n"
            + "    pan.pan.value = Math.max(-1, Math.min(1, (separation - 128) / 128.0));\n"
            + "    src.connect(gn); gn.connect(pan); pan.connect(audioContext.destination);\n"
            + "    src.start(0);\n"
            + "  } catch(e) { console.error('playSound error:', name, e); }\n"
            + "}\n"
            + "\n"
            // ── SoundFont MIDI music player ─────────────────────────────────────
            + "var _sfReady    = false;\n"
            + "var _mPlayer    = null;\n"
            + "var _sfInst     = {};\n"
            + "var _sfNodes    = {};\n"
            + "var _sfVolume   = 1.0;\n"
            + "var _chanVol    = {};\n"
            + "var _masterGain = null;\n"
            + "var _drumBuffers= {};\n"
            + "var _sfBase     = '/system/doom/music/sf/';\n"
            + "\n"
            + "var _gmNames = [\n"
            + "  'acoustic_grand_piano','bright_acoustic_piano','electric_grand_piano','honkytonk_piano',\n"
            + "  'electric_piano_1','electric_piano_2','harpsichord','clavinet',\n"
            + "  'celesta','glockenspiel','music_box','vibraphone','marimba','xylophone','tubular_bells','dulcimer',\n"
            + "  'drawbar_organ','percussive_organ','rock_organ','church_organ','reed_organ','accordion','harmonica','tango_accordion',\n"
            + "  'acoustic_guitar_nylon','acoustic_guitar_steel','electric_guitar_jazz','electric_guitar_clean',\n"
            + "  'electric_guitar_muted','overdriven_guitar','distortion_guitar','guitar_harmonics',\n"
            + "  'acoustic_bass','electric_bass_finger','electric_bass_pick','fretless_bass',\n"
            + "  'slap_bass_1','slap_bass_2','synth_bass_1','synth_bass_2',\n"
            + "  'violin','viola','cello','contrabass','tremolo_strings','pizzicato_strings','orchestral_harp','timpani',\n"
            + "  'string_ensemble_1','string_ensemble_2','synth_strings_1','synth_strings_2',\n"
            + "  'choir_aahs','voice_oohs','synth_voice','orchestra_hit',\n"
            + "  'trumpet','trombone','tuba','muted_trumpet','french_horn','brass_section','synth_brass_1','synth_brass_2',\n"
            + "  'soprano_sax','alto_sax','tenor_sax','baritone_sax',\n"
            + "  'oboe','english_horn','bassoon','clarinet',\n"
            + "  'piccolo','flute','recorder','pan_flute','blown_bottle','shakuhachi','whistle','ocarina',\n"
            + "  'lead_1_square','lead_2_sawtooth','lead_3_calliope','lead_4_chiff',\n"
            + "  'lead_5_charang','lead_6_voice','lead_7_fifths','lead_8_bass_lead',\n"
            + "  'pad_1_new_age','pad_2_warm','pad_3_polysynth','pad_4_choir',\n"
            + "  'pad_5_bowed','pad_6_metallic','pad_7_halo','pad_8_sweep',\n"
            + "  'fx_1_rain','fx_2_soundtrack','fx_3_crystal','fx_4_atmosphere',\n"
            + "  'fx_5_brightness','fx_6_goblins','fx_7_echoes','fx_8_sci_fi',\n"
            + "  'sitar','banjo','shamisen','koto','kalimba','bag_pipe','fiddle','shanai',\n"
            + "  'tinkle_bell','agogo','steel_drums','woodblock','taiko_drum','melodic_tom','synth_drum','reverse_cymbal',\n"
            + "  'guitar_fret_noise','breath_noise','seashore','bird_tweet',\n"
            + "  'telephone_ring','helicopter','applause','gunshot'\n"
            + "];\n"
            + "\n"
            + "function _loadInst(ch, prog) {\n"
            + "  if (!window.Soundfont || !audioContext || ch === 9) return;\n"
            + "  var name = _gmNames[prog & 127] || 'acoustic_grand_piano';\n"
            + "  if (_sfInst[ch] && _sfInst[ch]._sfName === name) return;\n"
            + "  Soundfont.instrument(audioContext, name, {\n"
            + "    soundfont: 'FluidR3_GM',\n"
            + "    nameToUrl: function(n) { return _sfBase + n + '-mp3.js'; },\n"
            + "    destination: _masterGain\n"
            + "  }).then(function(inst) { inst._sfName = name; _sfInst[ch] = inst; })\n"
            + "    .catch(function(e) { console.warn('[Music] Instrument load failed:', name, e); });\n"
            + "}\n"
            + "\n"
            + "function _initPercussion() {\n"
            + "  if (!window.MIDI) window.MIDI = {};\n"
            + "  if (!window.MIDI.Soundfont) window.MIDI.Soundfont = {};\n"
            + "  var s = document.createElement('script');\n"
            + "  s.src = _sfBase + 'percussion-mp3.js';\n"
            + "  s.onload = function() {\n"
            + "    var sf = window.MIDI.Soundfont.percussion;\n"
            + "    if (!sf) { console.warn('[Music] percussion soundfont missing'); return; }\n"
            + "    var noteMap = ['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B'];\n"
            + "    var keys = Object.keys(sf), total = keys.length, decoded = 0;\n"
            + "    keys.forEach(function(n) {\n"
            + "      var m = n.match(/^([A-G][b]?)(-?\\d+)$/);\n"
            + "      if (!m) return;\n"
            + "      var idx = noteMap.indexOf(m[1]); if (idx < 0) return;\n"
            + "      var midi = (parseInt(m[2]) + 1) * 12 + idx;\n"
            + "      if (midi < 0 || midi > 127) return;\n"
            + "      var dataUrl = sf[n], comma = dataUrl.indexOf(',');\n"
            + "      var b64 = dataUrl.substring(comma + 1);\n"
            + "      var bin = atob(b64), arr = new Uint8Array(bin.length);\n"
            + "      for (var i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);\n"
            + "      audioContext.decodeAudioData(arr.buffer, function(ab) {\n"
            + "        _drumBuffers[midi] = ab;\n"
            + "        if (++decoded === total) console.log('[Music] Percussion ready: ' + decoded + ' notes');\n"
            + "      }, function() {});\n"
            + "    });\n"
            + "  };\n"
            + "  s.onerror = function() { console.warn('[Music] percussion-mp3.js not found'); };\n"
            + "  document.head.appendChild(s);\n"
            + "}\n"
            + "\n"
            + "function _stopAll() {\n"
            + "  if (_mPlayer) { try { _mPlayer.stop(); } catch(e) {} _mPlayer = null; }\n"
            + "  var _now = audioContext ? audioContext.currentTime : 0;\n"
            + "  Object.keys(_sfNodes).forEach(function(k) {\n"
            + "    try { _sfNodes[k].stop(_now + 0.05); } catch(e) {}\n"
            + "  });\n"
            + "  _sfNodes = {};\n"
            + "}\n"
            + "\n"
            + "function _parseMidi(buf) {\n"
            + "  var d = new DataView(buf), p = 0;\n"
            + "  function u32() { var v = d.getUint32(p); p += 4; return v; }\n"
            + "  function u16() { var v = d.getUint16(p); p += 2; return v; }\n"
            + "  function u8()  { return d.getUint8(p++); }\n"
            + "  function vlq() { var v = 0, b; do { b = u8(); v = (v << 7) | (b & 0x7F); } while (b & 0x80); return v; }\n"
            + "  u32(); u32();\n"
            + "  var fmt = u16(), ntrk = u16(), rawDiv = u16();\n"
            + "  var isSmpte = !!(rawDiv & 0x8000), smpteRate = 0, div = 0;\n"
            + "  if (isSmpte) { var fps = 256 - ((rawDiv >> 8) & 0xFF); smpteRate = fps * (rawDiv & 0xFF); }\n"
            + "  else { div = rawDiv; }\n"
            + "  var tracks = [];\n"
            + "  for (var t = 0; t < ntrk; t++) {\n"
            + "    u32(); var end = p + u32();\n"
            + "    var evs = [], abs = 0, last = 0;\n"
            + "    while (p < end) {\n"
            + "      abs += vlq();\n"
            + "      var sb = u8();\n"
            + "      if (!(sb & 0x80)) { p--; sb = last; } else { last = sb; }\n"
            + "      var tp = sb >> 4, ech = sb & 0xF;\n"
            + "      if (tp === 0x9)      { var en = u8(), ev2 = u8(); evs.push({t:abs, type:ev2?'on':'off', ch:ech, note:en, vel:ev2}); }\n"
            + "      else if (tp === 0x8) { var en = u8(); u8();        evs.push({t:abs, type:'off',          ch:ech, note:en}); }\n"
            + "      else if (tp === 0xC) { var ep = u8();               evs.push({t:abs, type:'pc',           ch:ech, prog:ep}); }\n"
            + "      else if (tp === 0xA || tp === 0xE) { u8(); u8(); }\n"
            + "      else if (tp === 0xB) { var cn = u8(), cv = u8(); if (cn === 7 || cn === 11) evs.push({t:abs, type:'cc', ch:ech, cc:cn, val:cv}); }\n"
            + "      else if (tp === 0xD) { u8(); }\n"
            + "      else if (sb === 0xFF) {\n"
            + "        var mt = u8(), ml = vlq();\n"
            + "        if (mt === 0x51 && ml === 3) { var us = (u8() << 16) | (u8() << 8) | u8(); evs.push({t:abs, type:'tempo', us:us}); }\n"
            + "        else { p += ml; }\n"
            + "      } else if (sb === 0xF0 || sb === 0xF7) { p += vlq(); }\n"
            + "    }\n"
            + "    p = end; tracks.push(evs);\n"
            + "  }\n"
            + "  return { fmt:fmt, div:div, isSmpte:isSmpte, smpteRate:smpteRate, tracks:tracks };\n"
            + "}\n"
            + "\n"
            + "function _midi2sec(events, midi) {\n"
            + "  if (midi.isSmpte) {\n"
            + "    return events.map(function(ev) { return Object.assign({}, ev, {sec: ev.t / midi.smpteRate}); });\n"
            + "  }\n"
            + "  var out = [], usPerBeat = 500000, prevTick = 0, prevSec = 0;\n"
            + "  events.forEach(function(ev) {\n"
            + "    var sec = prevSec + (ev.t - prevTick) * usPerBeat / (midi.div * 1e6);\n"
            + "    if (ev.type === 'tempo') { prevSec = sec; prevTick = ev.t; usPerBeat = ev.us; }\n"
            + "    out.push(Object.assign({}, ev, {sec: sec}));\n"
            + "  });\n"
            + "  return out;\n"
            + "}\n"
            + "\n"
            + "function _scheduleMidi(timedEvs, loop) {\n"
            + "  var stopped = false, idx = 0, startAc = audioContext.currentTime, LEAD = 0.3;\n"
            + "  function pump() {\n"
            + "    if (stopped) return;\n"
            + "    var horizon = audioContext.currentTime - startAc + LEAD;\n"
            + "    while (idx < timedEvs.length) {\n"
            + "      var ev = timedEvs[idx];\n"
            + "      if (ev.sec > horizon) break;\n"
            + "      var at = startAc + ev.sec;\n"
            + "      if (ev.type === 'cc') {\n"
            + "        if (ev.cc === 7 || ev.cc === 11) _chanVol[ev.ch] = ev.val / 127;\n"
            + "      } else if (ev.type === 'pc') { _loadInst(ev.ch, ev.prog); }\n"
            + "      else if (ev.type === 'on') {\n"
            + "        if (ev.ch === 9) {\n"
            + "          var db = _drumBuffers[ev.note];\n"
            + "          if (db && _masterGain) {\n"
            + "            var src = audioContext.createBufferSource();\n"
            + "            src.buffer = db;\n"
            + "            var dg = audioContext.createGain();\n"
            + "            dg.gain.value = ev.vel / 127 * _sfVolume;\n"
            + "            src.connect(dg); dg.connect(_masterGain); src.start(at);\n"
            + "            _sfNodes['9_' + ev.note] = src;\n"
            + "          }\n"
            + "        } else {\n"
            + "          var inst = _sfInst[ev.ch];\n"
            + "          if (inst) {\n"
            + "            var chVol = (_chanVol[ev.ch] !== undefined) ? _chanVol[ev.ch] : 1.0;\n"
            + "            var nd = inst.play(ev.note, at, {gain: ev.vel / 127 * chVol * _sfVolume * 1.2});\n"
            + "            if (nd) _sfNodes[ev.ch + '_' + ev.note] = nd;\n"
            + "          }\n"
            + "        }\n"
            + "      } else if (ev.type === 'off') {\n"
            + "        var k = ev.ch + '_' + ev.note, nd = _sfNodes[k];\n"
            + "        if (nd) { try { nd.stop(at + 0.05); } catch(e) {} delete _sfNodes[k]; }\n"
            + "      }\n"
            + "      idx++;\n"
            + "    }\n"
            + "    if (idx >= timedEvs.length) {\n"
            + "      if (loop && !stopped) { idx = 0; startAc = audioContext.currentTime; setTimeout(pump, 50); }\n"
            + "    } else { setTimeout(pump, 25); }\n"
            + "  }\n"
            + "  pump();\n"
            + "  return { stop: function() { stopped = true; } };\n"
            + "}\n"
            + "\n"
            + "function startMidiPlayback(buf, loop) {\n"
            + "  if (!audioContext) return;\n"
            + "  _stopAll(); _chanVol = {};\n"
            + "  try {\n"
            + "    var midi = _parseMidi(buf);\n"
            + "    var allEvs = [];\n"
            + "    midi.tracks.forEach(function(tr) { tr.forEach(function(ev) { allEvs.push(ev); }); });\n"
            + "    allEvs.sort(function(a, b) { return a.t - b.t; });\n"
            + "    _mPlayer = _scheduleMidi(_midi2sec(allEvs, midi), loop);\n"
            + "  } catch(e) { console.error('[Music] MIDI parse error:', e); }\n"
            + "}\n"
            + "\n"
            + "function initMusicSystem() {\n"
            + "  if (!audioContext) return;\n"
            + "  var s1 = document.createElement('script');\n"
            + "  s1.src = '/system/doom/static/soundfont-player.min.js';\n"
            + "  s1.onload = function() {\n"
            + "    _sfReady = true;\n"
            + "    _initPercussion();\n"
            + "  };\n"
            + "  s1.onerror = function() { console.warn('[Music] soundfont-player failed to load'); };\n"
            + "  document.head.appendChild(s1);\n"
            + "}\n"
            + "\n"
            // ── Audio context lifecycle ─────────────────────────────────────────
            + "container.addEventListener('click', function() {\n"
            + "  if (!audioContext) { initAudio(); }\n"
            + "  else if (audioContext.state === 'suspended') { audioContext.resume(); }\n"
            + "});\n"
            + "window.addEventListener('focus', function() {\n"
            + "  if (audioContext && audioContext.state === 'suspended') audioContext.resume();\n"
            + "});\n"
            + "document.addEventListener('visibilitychange', function() {\n"
            + "  if (!document.hidden && audioContext && audioContext.state === 'suspended') audioContext.resume();\n"
            + "});\n"
            + "\n"
            // ── URL param auto-warp ─────────────────────────────────────────────
            + "(function() {\n"
            + "  var p = new URLSearchParams(window.location.search);\n"
            + "  var w = p.get('warp'), sk = p.get('skill');\n"
            + "  if (sk) _consoleExec('skill ' + sk);\n"
            + "  if (w) {\n"
            + "    var parts = w.split(',');\n"
            + "    _consoleExec('warp ' + parts.join(' ')).then(function(r) {\n"
            + "      _consoleLog('[URL] warp ' + parts.join(' '), r.message);\n"
            + "    }).catch(function() {});\n"
            + "  }\n"
            + "})();\n"
            + "\n"
            + "document.getElementById('sid').addEventListener('click', function() {\n"
            + "  navigator.clipboard.writeText(SESSION_ID).then(function() {\n"
            + "    var el = document.getElementById('sid');\n"
            + "    var prev = el.textContent;\n"
            + "    el.textContent = 'Copied!';\n"
            + "    el.style.color = '#88ff88';\n"
            + "    setTimeout(function() { el.textContent = prev; el.style.color = ''; }, 1200);\n"
            + "  }).catch(function() {});\n"
            + "});\n"
            + "\n"
            + "container.focus();\n"
            + "frameImg.src = '/system/doom/frame/stream?session=' + SESSION_ID;\n"
            + "console.log('DOOM Player ready. Session: ' + SESSION_ID + ' WAD: ' + WAD_NAME);\n"
            + "</script>\n"
            + "</body></html>";
    }

    /**
     * Returns the HTML page for a multiplayer match participant.
     * Uses /match/* endpoints instead of the single-player endpoints.
     *
     * Full audio (sound events + SoundFont MIDI music) via match endpoints.
     * Lobby overlay with shareable join URL shown until all players have joined.
     *
     * Audio note: sound events and music state are shared across all players on the same
     * engine session. The first player to poll each interval wins the events. This is an
     * acceptable MVP limitation for the shared-simulation architecture.
     *
     * @param matchId    Match UUID
     * @param sessionId  This browser's session UUID (used to identify the player slot)
     * @param slot       Player slot (0 = host, 1..N-1 = guests)
     * @param numPlayers Total player count for the match
     * @param wadName    WAD stem
     */
    public static String getMatchHTML(String matchId, String sessionId,
                                      int slot, int numPlayers, String wadName) {
        String safeMatch   = matchId.replace("'", "\\'");
        String safeSession = sessionId.replace("'", "\\'");
        String safeWad     = wadName.replace("'", "\\'");
        String playerLabel = "Player " + (slot + 1) + " of " + numPlayers;
        // Lobby overlay is hidden immediately for the last player to join
        String lobbyDisplay = (slot + 1 >= numPlayers) ? "none" : "flex";

        return "<!DOCTYPE html>\n"
            + "<html><head>\n"
            + "<meta charset='UTF-8'>\n"
            + "<title>DOOM Deathmatch - " + escapeHtml(wadName) + "</title>\n"
            + "<style>\n"
            + "* { margin:0; padding:0; box-sizing:border-box; }\n"
            + "html, body { width:100%; height:100%; overflow:hidden; }\n"
            + "body { background:#1a1a1a; color:#fff; font-family:monospace; font-size:14px; display:flex; flex-direction:column; }\n"
            + "#controls { flex-shrink:0; text-align:center; padding:8px 15px; background:#222; }\n"
            + "#game-container { flex:1; min-height:0; background:#000; position:relative; outline:none; }\n"
            + "#game-container:focus { outline: 3px solid #c0392b; cursor: none; }\n"
            + "#frame { width:100%; height:100%; object-fit:contain; object-position:center; image-rendering:pixelated; image-rendering:-moz-crisp-edges; image-rendering:crisp-edges; }\n"
            + "#status { flex-shrink:0; padding:4px; font-size:12px; color:#888; text-align:center; background:#1a1a1a; }\n"
            + ".stat { display:inline-block; margin:0 10px; }\n"
            + "#latency { display:inline-block; min-width:4ch; text-align:right; }\n"
            + "#matchStatus { color:#ffcc00; }\n"
            + "#doomConsole { display:none; position:fixed; bottom:0; left:0; right:0; background:rgba(0,0,0,0.88); color:#00ff00; font:14px monospace; padding:8px 12px; z-index:9999; border-top:2px solid #00ff00; }\n"
            + "#consoleOut { max-height:110px; overflow-y:auto; margin-bottom:4px; font-size:12px; line-height:1.4; }\n"
            + ".con-row { display:flex; align-items:center; gap:6px; }\n"
            + "#consoleIn { flex:1; background:transparent; border:none; outline:none; color:#00ff00; font:14px monospace; caret-color:#00ff00; width:100%; }\n"
            // ── Lobby overlay ──────────────────────────────────────────────────
            + "#lobby-overlay {\n"
            + "  display:" + lobbyDisplay + "; position:absolute; top:0; left:0; right:0; bottom:0;\n"
            + "  background:rgba(0,0,0,0.88); flex-direction:column; align-items:center;\n"
            + "  justify-content:center; z-index:100; cursor:default;\n"
            + "}\n"
            + "#lobby-overlay.hidden { display:none; }\n"
            + "#lobby-title { font-size:26px; font-weight:bold; letter-spacing:8px; color:#ff4444; text-transform:uppercase; margin-bottom:18px; }\n"
            + "#lobby-count { font-size:20px; color:#ffcc00; margin-bottom:24px; }\n"
            + "#lobby-url-label { color:#888; font-size:12px; margin-bottom:8px; }\n"
            + "#lobby-url {\n"
            + "  color:#88ff88; font-size:12px; word-break:break-all; width:min(680px,90%);\n"
            + "  text-align:center; cursor:pointer;\n"
            + "  padding:6px 12px; border:1px solid #336633; background:#0a1a0a;\n"
            + "  font-family:monospace; outline:none; caret-color:transparent;\n"
            + "}\n"
            + "#lobby-url:hover { background:#0f2a0f; }\n"
            + "#lobby-copy-hint { color:#555; font-size:11px; margin-top:6px; }\n"
            + "#lobby-copied { color:#88ff88; font-size:11px; margin-top:4px; visibility:hidden; }\n"
            + "</style>\n"
            + "</head><body>\n"
            + "<div id='controls'>\n"
            + "  <strong style='color:#c0392b; letter-spacing:4px'>DEATHMATCH</strong> | Arrow Keys = Move/Turn | Ctrl = Fire | Space = Use | Esc = Menu | ~ = Console<br>\n"
            + "  <small style='color:#888'><span style='color:#ddd'>" + escapeHtml(wadName) + "</span>"
            + " | " + escapeHtml(playerLabel)
            + " | Match: " + matchId + "</small>\n"
            + "</div>\n"
            + "<div id='game-container' tabindex='0'>\n"
            + "  <img id='frame' alt='DOOM Frame'/>\n"
            // ── Lobby overlay HTML ─────────────────────────────────────────────
            + "  <div id='lobby-overlay'>\n"
            + "    <div id='lobby-title'>Deathmatch</div>\n"
            + "    <div id='lobby-count'>1 / " + numPlayers + " players joined</div>\n"
            + "    <div id='lobby-url-label'>Share this link with other players:</div>\n"
            + "    <input id='lobby-url' type='text' readonly/>\n"
            + "    <div id='lobby-copy-hint'>(click to copy)</div>\n"
            + "    <div id='lobby-copied'>Copied!</div>\n"
            + "  </div>\n"
            + "</div>\n"
            + "<div id='status'>\n"
            + "  <span class='stat'>Latency: <span id='latency'>--</span>ms</span>\n"
            + "  <span class='stat' id='matchStatus'>Connecting...</span>\n"
            + "  <span class='stat' style='color:#555'>" + escapeHtml(playerLabel) + "</span>\n"
            + "</div>\n"
            + "<div id='doomConsole'>\n"
            + "  <div id='consoleOut'></div>\n"
            + "  <div class='con-row'><span>&gt;</span>\n"
            + "    <input id='consoleIn' type='text' autocomplete='off' placeholder='warp E M | skill 4 | god | noclip | give all | help'/>\n"
            + "  </div>\n"
            + "</div>\n"
            + "<script>\n"
            + "var MATCH_ID    = '" + safeMatch + "';\n"
            + "var SESSION_ID  = '" + safeSession + "';\n"
            + "var WAD_NAME    = '" + safeWad + "';\n"
            + "var PLAYER_SLOT = " + slot + ";\n"
            + "var NUM_PLAYERS = " + numPlayers + ";\n"
            + "sessionStorage.setItem('doomMatchId',   MATCH_ID);\n"
            + "sessionStorage.setItem('doomSessionId', SESSION_ID);\n"
            + "(function(){ var a=new URLSearchParams(location.search).get('auth'); if(a) sessionStorage.setItem('doomPlayToken',a); })();\n"
            + "var _matchParams = '?match=' + MATCH_ID + '&session=' + SESSION_ID;\n"
            + "\n"
            + "var container     = document.getElementById('game-container');\n"
            + "var frameImg      = document.getElementById('frame');\n"
            + "var latencyEl     = document.getElementById('latency');\n"
            + "var matchStatusEl = document.getElementById('matchStatus');\n"
            + "var lobbyOverlay  = document.getElementById('lobby-overlay');\n"
            + "var lobbyCount    = document.getElementById('lobby-count');\n"
            + "var lobbyUrl      = document.getElementById('lobby-url');\n"
            + "\n"
            // ── Lobby overlay init ──────────────────────────────────────────────
            + "(function() {\n"
            + "  var _authTok = sessionStorage.getItem('doomPlayToken')\n"
            + "              || new URLSearchParams(location.search).get('auth')\n"
            + "              || '';\n"
            + "  var joinUrl = window.location.origin + '/system/doom/match/join?match=' + MATCH_ID\n"
            + "              + '&wad=' + encodeURIComponent(WAD_NAME)\n"
            + "              + (_authTok ? '&auth=' + encodeURIComponent(_authTok) : '');\n"
            + "  lobbyUrl.value = joinUrl;\n"
            + "  function _copyLobbyUrl() {\n"
            + "    lobbyUrl.select();\n"
            + "    var c = document.getElementById('lobby-copied');\n"
            + "    function _flash() { c.style.visibility='visible'; setTimeout(function(){ c.style.visibility='hidden'; }, 1500); }\n"
            + "    if (navigator.clipboard && navigator.clipboard.writeText) {\n"
            + "      navigator.clipboard.writeText(joinUrl).then(_flash).catch(function() {\n"
            + "        try { document.execCommand('copy'); _flash(); } catch(e) {}\n"
            + "      });\n"
            + "    } else {\n"
            + "      try { document.execCommand('copy'); _flash(); } catch(e) {}\n"
            + "    }\n"
            + "  }\n"
            + "  lobbyUrl.addEventListener('click', _copyLobbyUrl);\n"
            + "})();\n"
            + "\n"
            + "var pressed = {};\n"
            + "\n"
            // ── Console overlay ─────────────────────────────────────────────────
            + "var _consoleOpen = false;\n"
            + "function _consoleToggle() {\n"
            + "  _consoleOpen = !_consoleOpen;\n"
            + "  document.getElementById('doomConsole').style.display = _consoleOpen ? 'block' : 'none';\n"
            + "  if (_consoleOpen) {\n"
            + "    pressed = {}; sendState();\n"
            + "    document.getElementById('consoleIn').focus();\n"
            + "  } else { container.focus(); }\n"
            + "}\n"
            + "function _consoleLog(prompt, msg) {\n"
            + "  var out = document.getElementById('consoleOut');\n"
            + "  out.innerHTML += '<div><span style=\"color:#aaa\">&gt; ' + prompt + '</span></div>';\n"
            + "  if (msg) out.innerHTML += '<div>' + msg + '</div>';\n"
            + "  out.scrollTop = out.scrollHeight;\n"
            + "}\n"
            + "function _consoleExec(cmd) {\n"
            + "  return fetch('/system/doom/match/console' + _matchParams, {\n"
            + "    method:'POST', headers:{'Content-Type':'application/x-www-form-urlencoded'},\n"
            + "    body:'command=' + encodeURIComponent(cmd)\n"
            + "  }).then(function(r) { return r.json(); });\n"
            + "}\n"
            + "document.getElementById('consoleIn').addEventListener('keydown', function(e) {\n"
            + "  e.stopPropagation();\n"
            + "  if (e.key === 'Escape') { _consoleToggle(); return; }\n"
            + "  if (e.key !== 'Enter') return;\n"
            + "  var cmd = this.value.trim(); this.value = '';\n"
            + "  if (!cmd) { _consoleToggle(); return; }\n"
            + "  _consoleExec(cmd).then(function(r) { _consoleLog(cmd, r.message); })\n"
            + "    .catch(function() { _consoleLog(cmd, 'Error: server unreachable'); });\n"
            + "});\n"
            + "\n"
            // ── Game ended overlay ──────────────────────────────────────────────
            + "var gameEnded = false;\n"
            + "var _evtSource = null, _ws = null, _wsOk = false;\n"
            + "function showGameEnded() {\n"
            + "  gameEnded = true;\n"
            + "  if (_evtSource) { _evtSource.close(); _evtSource = null; }\n"
            + "  if (_ws) { _ws.close(); _ws = null; }\n"
            + "  if (typeof _stopAll === 'function') _stopAll();\n"
            + "  var ov = document.createElement('div');\n"
            + "  ov.style.cssText = 'position:fixed;inset:0;background:#000;color:#c00;display:flex;flex-direction:column;align-items:center;justify-content:center;font:bold 28px monospace;z-index:999';\n"
            + "  ov.innerHTML = '<div>GAME ENDED</div><div style=\"font-size:14px;color:#888;margin-top:16px\">You may close this browser tab.</div>';\n"
            + "  document.body.appendChild(ov);\n"
            + "}\n"
            + "\n"
            // ── MJPEG push stream ────────────────────────────────────────────────
            + "frameImg.onload = function() {};\n"
            + "frameImg.onerror = function() {\n"
            + "  if (!gameEnded) {\n"
            + "    fetch('/system/doom/match/frame' + _matchParams)\n"
            + "      .then(function(r) { if (r.status === 410) showGameEnded(); })\n"
            + "      .catch(function() {});\n"
            + "  }\n"
            + "};\n"
            + "\n"
            // ── Input: WebSocket preferred, POST fallback ────────────────────────
            + "function sendState() {\n"
            + "  if (gameEnded) return;\n"
            + "  if (_ws && _ws.readyState === 1) { _ws.send(Object.keys(pressed).join(',')); return; }\n"
            + "  fetch('/system/doom/match/input' + _matchParams, {\n"
            + "    method:'POST', headers:{'Content-Type':'text/plain'},\n"
            + "    body: Object.keys(pressed).join(',')\n"
            + "  }).catch(function(){});\n"
            + "}\n"
            + "container.addEventListener('keydown', function(e) {\n"
            + "  if (!audioContext) { initAudio(); } else if (audioContext.state === 'suspended') { audioContext.resume(); }\n"
            + "  if (e.key==='`' || e.keyCode===192) { e.preventDefault(); _consoleToggle(); return; }\n"
            + "  if (_consoleOpen) return;\n"
            + "  e.preventDefault(); e.stopPropagation();\n"
            + "  if (!pressed[e.keyCode]) { pressed[e.keyCode]=true; sendState(); }\n"
            + "});\n"
            + "container.addEventListener('keyup', function(e) {\n"
            + "  e.preventDefault(); e.stopPropagation();\n"
            + "  if (pressed[e.keyCode]) { delete pressed[e.keyCode]; sendState(); }\n"
            + "});\n"
            + "container.addEventListener('blur', function() { pressed={}; sendState(); });\n"
            + "window.addEventListener('blur', function() { pressed={}; sendState(); });\n"
            + "\n"
            // ── SSE: sound + music + latency events (match) ──────────────────────
            + "function _openEvents() {\n"
            + "  if (gameEnded) return;\n"
            + "  _evtSource = new EventSource('/system/doom/match/events/stream' + _matchParams);\n"
            + "  _evtSource.addEventListener('sound', function(e) {\n"
            + "    if (!audioContext) return;\n"
            + "    JSON.parse(e.data).forEach(function(ev) { playSound(ev.name,ev.volume,ev.separation,ev.pitch); });\n"
            + "  });\n"
            + "  _evtSource.addEventListener('music', function(e) {\n"
            + "    var s = JSON.parse(e.data);\n"
            + "    _sfVolume = (s.volume !== undefined) ? s.volume / 127 : 1.0;\n"
            + "    if (s.playing && s.changed) {\n"
            + "      fetch('/system/doom/match/music/midi' + _matchParams)\n"
            + "        .then(function(r) { return r.arrayBuffer(); })\n"
            + "        .then(function(buf) { startMidiPlayback(buf, s.looping); })\n"
            + "        .catch(function(e) { console.warn('[Music] MIDI fetch failed:', e); });\n"
            + "    } else if (!s.playing) { _stopAll(); }\n"
            + "  });\n"
            + "  _evtSource.addEventListener('ping', function(e) {\n"
            + "    var ms = Date.now() - parseInt(e.data);\n"
            + "    latencyEl.textContent = ms;\n"
            + "    latencyEl.style.color = ms<50?'#4db87a':ms<150?'#c88a00':'#c0392b';\n"
            + "  });\n"
            + "  _evtSource.onerror = function() { if (!gameEnded && streamStarted) { _evtSource.close(); _evtSource = null; setTimeout(_openEvents, 1000); } };\n"
            + "}\n"
            + "\n"
            // ── WebSocket: bidirectional input + audio (with SSE fallback) ───────
            + "function _connectWS() {\n"
            + "  if (gameEnded) return;\n"
            + "  var _wsTimer = setTimeout(function() { if (_ws && _ws.readyState === 0) _ws.close(); }, 2000);\n"
            + "  var proto = location.protocol === 'https:' ? 'wss:' : 'ws:';\n"
            + "  _ws = new WebSocket(proto + '//' + location.host + '/system/doom-ws' + _matchParams);\n"
            + "  _ws.onopen = function() {\n"
            + "    clearTimeout(_wsTimer); _wsOk = true;\n"
            + "    console.log('[DOOM] WS connected — using WebSocket transport');\n"
            + "    if (_evtSource) { _evtSource.onerror = null; _evtSource.close(); _evtSource = null; }\n"
            + "  };\n"
            + "  _ws.onmessage = function(e) {\n"
            + "    var d = e.data;\n"
            + "    if (d.startsWith('pong:')) {\n"
            + "      var ms = Date.now() - parseInt(d.substring(5));\n"
            + "      latencyEl.textContent = ms;\n"
            + "      latencyEl.style.color = ms<50?'#4db87a':ms<150?'#c88a00':'#c0392b';\n"
            + "    } else if (d.startsWith('sound:')) {\n"
            + "      if (audioContext) JSON.parse(d.substring(6)).forEach(function(ev) { playSound(ev.name,ev.volume,ev.separation,ev.pitch); });\n"
            + "    } else if (d.startsWith('music:')) {\n"
            + "      var s = JSON.parse(d.substring(6));\n"
            + "      _sfVolume = (s.volume !== undefined) ? s.volume / 127 : 1.0;\n"
            + "      if (s.playing && s.changed) {\n"
            + "        fetch('/system/doom/match/music/midi' + _matchParams)\n"
            + "          .then(function(r) { return r.arrayBuffer(); })\n"
            + "          .then(function(buf) { startMidiPlayback(buf, s.looping); })\n"
            + "          .catch(function(e) { console.warn('[Music] MIDI fetch failed:', e); });\n"
            + "      } else if (!s.playing) { _stopAll(); }\n"
            + "    }\n"
            + "  };\n"
            + "  _ws.onclose = function() {\n"
            + "    clearTimeout(_wsTimer); _ws = null;\n"
            + "    if (!gameEnded) {\n"
            + "      if (_wsOk) { _wsOk = false; console.log('[DOOM] WS dropped — reconnecting...'); setTimeout(_connectWS, 1000); }\n"
            + "      else { console.warn('[DOOM] WS unavailable — falling back to SSE+POST'); if (!_evtSource) { _openEvents(); } }\n"
            + "    }\n"
            + "  };\n"
            + "  _ws.onerror = function() {};\n"
            + "}\n"
            + "setInterval(function() { if (_ws && _ws.readyState === 1) _ws.send('ping:' + Date.now()); }, 2000);\n"
            + "\n"
            // ── Web Audio API sound system (match endpoints) ─────────────────────
            + "var audioContext = null;\n"
            + "var soundBuffers = {};\n"
            + "var soundsLoaded = false;\n"
            + "\n"
            + "function initAudio() {\n"
            + "  try {\n"
            + "    audioContext = new (window.AudioContext || window.webkitAudioContext)();\n"
            + "    console.log('[Sound] initAudio: AudioContext created, state=' + audioContext.state);\n"
            + "    _masterGain = audioContext.createGain(); _masterGain.gain.value = 0.9;\n"
            + "    var _eq1 = audioContext.createBiquadFilter();\n"
            + "    _eq1.type = 'lowshelf'; _eq1.frequency.value = 100; _eq1.gain.value = 4;\n"
            + "    var _eq2 = audioContext.createBiquadFilter();\n"
            + "    _eq2.type = 'peaking'; _eq2.frequency.value = 900; _eq2.Q.value = 2; _eq2.gain.value = -3;\n"
            + "    var _eq3 = audioContext.createBiquadFilter();\n"
            + "    _eq3.type = 'highshelf'; _eq3.frequency.value = 5500; _eq3.gain.value = -2;\n"
            + "    _masterGain.connect(_eq1); _eq1.connect(_eq2); _eq2.connect(_eq3); _eq3.connect(audioContext.destination);\n"
            + "    loadSounds();\n"
            + "    initMusicSystem();\n"
            + "  } catch(e) { console.error('[Sound] Web Audio API error:', e); }\n"
            + "}\n"
            + "\n"
            + "var _soundLoadAttempts = 0;\n"
            + "function loadSounds() {\n"
            + "  fetch('/system/doom/match/sounds' + _matchParams)\n"
            + "    .then(function(r) { return r.json(); })\n"
            + "    .then(function(names) {\n"
            + "      if (names.length === 0) {\n"
            + "        if (++_soundLoadAttempts < 10) {\n"
            + "          setTimeout(loadSounds, 3000);\n"
            + "        } else { console.warn('[Sound] cache never became ready after 10 attempts'); }\n"
            + "        return;\n"
            + "      }\n"
            + "      var n = names.length, done = 0;\n"
            + "      names.forEach(function(name) {\n"
            + "        fetch('/system/doom/match/sounds/' + name + _matchParams)\n"
            + "          .then(function(r) { return r.arrayBuffer(); })\n"
            + "          .then(function(buf) { return audioContext.decodeAudioData(buf); })\n"
            + "          .then(function(ab) { soundBuffers[name] = ab; if (++done === n) soundsLoaded = true; })\n"
            + "          .catch(function(e) { console.error('[Sound] load fail:', name, e); });\n"
            + "      });\n"
            + "    })\n"
            + "    .catch(function(e) { console.error('[Sound] list fetch fail:', e); });\n"
            + "}\n"
            + "\n"
            + "function playSound(name, volume, separation, pitch) {\n"
            + "  if (!audioContext || !soundsLoaded) return;\n"
            + "  var buf = soundBuffers[name]; if (!buf) return;\n"
            + "  try {\n"
            + "    var src = audioContext.createBufferSource();\n"
            + "    src.buffer = buf;\n"
            + "    src.playbackRate.value = pitch / 128.0;\n"
            + "    var gn = audioContext.createGain();\n"
            + "    gn.gain.value = Math.min(1.0, volume / 127.0);\n"
            + "    var pan = audioContext.createStereoPanner();\n"
            + "    pan.pan.value = Math.max(-1, Math.min(1, (separation - 128) / 128.0));\n"
            + "    src.connect(gn); gn.connect(pan); pan.connect(audioContext.destination);\n"
            + "    src.start(0);\n"
            + "  } catch(e) { console.error('playSound error:', name, e); }\n"
            + "}\n"
            + "\n"
            // ── SoundFont MIDI music player (match endpoints) ────────────────────
            + "var _sfReady    = false;\n"
            + "var _mPlayer    = null;\n"
            + "var _sfInst     = {};\n"
            + "var _sfNodes    = {};\n"
            + "var _sfVolume   = 1.0;\n"
            + "var _chanVol    = {};\n"
            + "var _masterGain = null;\n"
            + "var _drumBuffers= {};\n"
            + "var _sfBase     = '/system/doom/music/sf/';\n"
            + "\n"
            + "var _gmNames = [\n"
            + "  'acoustic_grand_piano','bright_acoustic_piano','electric_grand_piano','honkytonk_piano',\n"
            + "  'electric_piano_1','electric_piano_2','harpsichord','clavinet',\n"
            + "  'celesta','glockenspiel','music_box','vibraphone','marimba','xylophone','tubular_bells','dulcimer',\n"
            + "  'drawbar_organ','percussive_organ','rock_organ','church_organ','reed_organ','accordion','harmonica','tango_accordion',\n"
            + "  'acoustic_guitar_nylon','acoustic_guitar_steel','electric_guitar_jazz','electric_guitar_clean',\n"
            + "  'electric_guitar_muted','overdriven_guitar','distortion_guitar','guitar_harmonics',\n"
            + "  'acoustic_bass','electric_bass_finger','electric_bass_pick','fretless_bass',\n"
            + "  'slap_bass_1','slap_bass_2','synth_bass_1','synth_bass_2',\n"
            + "  'violin','viola','cello','contrabass','tremolo_strings','pizzicato_strings','orchestral_harp','timpani',\n"
            + "  'string_ensemble_1','string_ensemble_2','synth_strings_1','synth_strings_2',\n"
            + "  'choir_aahs','voice_oohs','synth_voice','orchestra_hit',\n"
            + "  'trumpet','trombone','tuba','muted_trumpet','french_horn','brass_section','synth_brass_1','synth_brass_2',\n"
            + "  'soprano_sax','alto_sax','tenor_sax','baritone_sax',\n"
            + "  'oboe','english_horn','bassoon','clarinet',\n"
            + "  'piccolo','flute','recorder','pan_flute','blown_bottle','shakuhachi','whistle','ocarina',\n"
            + "  'lead_1_square','lead_2_sawtooth','lead_3_calliope','lead_4_chiff',\n"
            + "  'lead_5_charang','lead_6_voice','lead_7_fifths','lead_8_bass_lead',\n"
            + "  'pad_1_new_age','pad_2_warm','pad_3_polysynth','pad_4_choir',\n"
            + "  'pad_5_bowed','pad_6_metallic','pad_7_halo','pad_8_sweep',\n"
            + "  'fx_1_rain','fx_2_soundtrack','fx_3_crystal','fx_4_atmosphere',\n"
            + "  'fx_5_brightness','fx_6_goblins','fx_7_echoes','fx_8_sci_fi',\n"
            + "  'sitar','banjo','shamisen','koto','kalimba','bag_pipe','fiddle','shanai',\n"
            + "  'tinkle_bell','agogo','steel_drums','woodblock','taiko_drum','melodic_tom','synth_drum','reverse_cymbal',\n"
            + "  'guitar_fret_noise','breath_noise','seashore','bird_tweet',\n"
            + "  'telephone_ring','helicopter','applause','gunshot'\n"
            + "];\n"
            + "\n"
            + "function _loadInst(ch, prog) {\n"
            + "  if (!window.Soundfont || !audioContext || ch === 9) return;\n"
            + "  var name = _gmNames[prog & 127] || 'acoustic_grand_piano';\n"
            + "  if (_sfInst[ch] && _sfInst[ch]._sfName === name) return;\n"
            + "  Soundfont.instrument(audioContext, name, {\n"
            + "    soundfont: 'FluidR3_GM',\n"
            + "    nameToUrl: function(n) { return _sfBase + n + '-mp3.js'; },\n"
            + "    destination: _masterGain\n"
            + "  }).then(function(inst) { inst._sfName = name; _sfInst[ch] = inst; })\n"
            + "    .catch(function(e) { console.warn('[Music] Instrument load failed:', name, e); });\n"
            + "}\n"
            + "\n"
            + "function _initPercussion() {\n"
            + "  if (!window.MIDI) window.MIDI = {};\n"
            + "  if (!window.MIDI.Soundfont) window.MIDI.Soundfont = {};\n"
            + "  var s = document.createElement('script');\n"
            + "  s.src = _sfBase + 'percussion-mp3.js';\n"
            + "  s.onload = function() {\n"
            + "    var sf = window.MIDI.Soundfont.percussion;\n"
            + "    if (!sf) { console.warn('[Music] percussion soundfont missing'); return; }\n"
            + "    var noteMap = ['C','Db','D','Eb','E','F','Gb','G','Ab','A','Bb','B'];\n"
            + "    var keys = Object.keys(sf), total = keys.length, decoded = 0;\n"
            + "    keys.forEach(function(n) {\n"
            + "      var m = n.match(/^([A-G][b]?)(-?\\d+)$/);\n"
            + "      if (!m) return;\n"
            + "      var idx = noteMap.indexOf(m[1]); if (idx < 0) return;\n"
            + "      var midi = (parseInt(m[2]) + 1) * 12 + idx;\n"
            + "      if (midi < 0 || midi > 127) return;\n"
            + "      var dataUrl = sf[n], comma = dataUrl.indexOf(',');\n"
            + "      var b64 = dataUrl.substring(comma + 1);\n"
            + "      var bin = atob(b64), arr = new Uint8Array(bin.length);\n"
            + "      for (var i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);\n"
            + "      audioContext.decodeAudioData(arr.buffer, function(ab) {\n"
            + "        _drumBuffers[midi] = ab;\n"
            + "        if (++decoded === total) console.log('[Music] Percussion ready: ' + decoded + ' notes');\n"
            + "      }, function() {});\n"
            + "    });\n"
            + "  };\n"
            + "  s.onerror = function() { console.warn('[Music] percussion-mp3.js not found'); };\n"
            + "  document.head.appendChild(s);\n"
            + "}\n"
            + "\n"
            + "function _stopAll() {\n"
            + "  if (_mPlayer) { try { _mPlayer.stop(); } catch(e) {} _mPlayer = null; }\n"
            + "  var _now = audioContext ? audioContext.currentTime : 0;\n"
            + "  Object.keys(_sfNodes).forEach(function(k) {\n"
            + "    try { _sfNodes[k].stop(_now + 0.05); } catch(e) {}\n"
            + "  });\n"
            + "  _sfNodes = {};\n"
            + "}\n"
            + "\n"
            + "function _parseMidi(buf) {\n"
            + "  var d = new DataView(buf), p = 0;\n"
            + "  function u32() { var v = d.getUint32(p); p += 4; return v; }\n"
            + "  function u16() { var v = d.getUint16(p); p += 2; return v; }\n"
            + "  function u8()  { return d.getUint8(p++); }\n"
            + "  function vlq() { var v = 0, b; do { b = u8(); v = (v << 7) | (b & 0x7F); } while (b & 0x80); return v; }\n"
            + "  u32(); u32();\n"
            + "  var fmt = u16(), ntrk = u16(), rawDiv = u16();\n"
            + "  var isSmpte = !!(rawDiv & 0x8000), smpteRate = 0, div = 0;\n"
            + "  if (isSmpte) { var fps = 256 - ((rawDiv >> 8) & 0xFF); smpteRate = fps * (rawDiv & 0xFF); }\n"
            + "  else { div = rawDiv; }\n"
            + "  var tracks = [];\n"
            + "  for (var t = 0; t < ntrk; t++) {\n"
            + "    u32(); var end = p + u32();\n"
            + "    var evs = [], abs = 0, last = 0;\n"
            + "    while (p < end) {\n"
            + "      abs += vlq();\n"
            + "      var sb = u8();\n"
            + "      if (!(sb & 0x80)) { p--; sb = last; } else { last = sb; }\n"
            + "      var tp = sb >> 4, ech = sb & 0xF;\n"
            + "      if (tp === 0x9)      { var en = u8(), ev2 = u8(); evs.push({t:abs, type:ev2?'on':'off', ch:ech, note:en, vel:ev2}); }\n"
            + "      else if (tp === 0x8) { var en = u8(); u8();        evs.push({t:abs, type:'off',          ch:ech, note:en}); }\n"
            + "      else if (tp === 0xC) { var ep = u8();               evs.push({t:abs, type:'pc',           ch:ech, prog:ep}); }\n"
            + "      else if (tp === 0xA || tp === 0xE) { u8(); u8(); }\n"
            + "      else if (tp === 0xB) { var cn = u8(), cv = u8(); if (cn === 7 || cn === 11) evs.push({t:abs, type:'cc', ch:ech, cc:cn, val:cv}); }\n"
            + "      else if (tp === 0xD) { u8(); }\n"
            + "      else if (sb === 0xFF) {\n"
            + "        var mt = u8(), ml = vlq();\n"
            + "        if (mt === 0x51 && ml === 3) { var us = (u8() << 16) | (u8() << 8) | u8(); evs.push({t:abs, type:'tempo', us:us}); }\n"
            + "        else { p += ml; }\n"
            + "      } else if (sb === 0xF0 || sb === 0xF7) { p += vlq(); }\n"
            + "    }\n"
            + "    p = end; tracks.push(evs);\n"
            + "  }\n"
            + "  return { fmt:fmt, div:div, isSmpte:isSmpte, smpteRate:smpteRate, tracks:tracks };\n"
            + "}\n"
            + "\n"
            + "function _midi2sec(events, midi) {\n"
            + "  if (midi.isSmpte) {\n"
            + "    return events.map(function(ev) { return Object.assign({}, ev, {sec: ev.t / midi.smpteRate}); });\n"
            + "  }\n"
            + "  var out = [], usPerBeat = 500000, prevTick = 0, prevSec = 0;\n"
            + "  events.forEach(function(ev) {\n"
            + "    var sec = prevSec + (ev.t - prevTick) * usPerBeat / (midi.div * 1e6);\n"
            + "    if (ev.type === 'tempo') { prevSec = sec; prevTick = ev.t; usPerBeat = ev.us; }\n"
            + "    out.push(Object.assign({}, ev, {sec: sec}));\n"
            + "  });\n"
            + "  return out;\n"
            + "}\n"
            + "\n"
            + "function _scheduleMidi(timedEvs, loop) {\n"
            + "  var stopped = false, idx = 0, startAc = audioContext.currentTime, LEAD = 0.3;\n"
            + "  function pump() {\n"
            + "    if (stopped) return;\n"
            + "    var horizon = audioContext.currentTime - startAc + LEAD;\n"
            + "    while (idx < timedEvs.length) {\n"
            + "      var ev = timedEvs[idx];\n"
            + "      if (ev.sec > horizon) break;\n"
            + "      var at = startAc + ev.sec;\n"
            + "      if (ev.type === 'cc') {\n"
            + "        if (ev.cc === 7 || ev.cc === 11) _chanVol[ev.ch] = ev.val / 127;\n"
            + "      } else if (ev.type === 'pc') { _loadInst(ev.ch, ev.prog); }\n"
            + "      else if (ev.type === 'on') {\n"
            + "        if (ev.ch === 9) {\n"
            + "          var db = _drumBuffers[ev.note];\n"
            + "          if (db && _masterGain) {\n"
            + "            var src = audioContext.createBufferSource();\n"
            + "            src.buffer = db;\n"
            + "            var dg = audioContext.createGain();\n"
            + "            dg.gain.value = ev.vel / 127 * _sfVolume;\n"
            + "            src.connect(dg); dg.connect(_masterGain); src.start(at);\n"
            + "            _sfNodes['9_' + ev.note] = src;\n"
            + "          }\n"
            + "        } else {\n"
            + "          var inst = _sfInst[ev.ch];\n"
            + "          if (inst) {\n"
            + "            var chVol = (_chanVol[ev.ch] !== undefined) ? _chanVol[ev.ch] : 1.0;\n"
            + "            var nd = inst.play(ev.note, at, {gain: ev.vel / 127 * chVol * _sfVolume * 1.2});\n"
            + "            if (nd) _sfNodes[ev.ch + '_' + ev.note] = nd;\n"
            + "          }\n"
            + "        }\n"
            + "      } else if (ev.type === 'off') {\n"
            + "        var k = ev.ch + '_' + ev.note, nd = _sfNodes[k];\n"
            + "        if (nd) { try { nd.stop(at + 0.05); } catch(e) {} delete _sfNodes[k]; }\n"
            + "      }\n"
            + "      idx++;\n"
            + "    }\n"
            + "    if (idx >= timedEvs.length) {\n"
            + "      if (loop && !stopped) { idx = 0; startAc = audioContext.currentTime; setTimeout(pump, 50); }\n"
            + "    } else { setTimeout(pump, 25); }\n"
            + "  }\n"
            + "  pump();\n"
            + "  return { stop: function() { stopped = true; } };\n"
            + "}\n"
            + "\n"
            + "function startMidiPlayback(buf, loop) {\n"
            + "  if (!audioContext) return;\n"
            + "  _stopAll(); _chanVol = {};\n"
            + "  try {\n"
            + "    var midi = _parseMidi(buf);\n"
            + "    var allEvs = [];\n"
            + "    midi.tracks.forEach(function(tr) { tr.forEach(function(ev) { allEvs.push(ev); }); });\n"
            + "    allEvs.sort(function(a, b) { return a.t - b.t; });\n"
            + "    _mPlayer = _scheduleMidi(_midi2sec(allEvs, midi), loop);\n"
            + "  } catch(e) { console.error('[Music] MIDI parse error:', e); }\n"
            + "}\n"
            + "\n"
            + "function initMusicSystem() {\n"
            + "  if (!audioContext) return;\n"
            + "  var s1 = document.createElement('script');\n"
            + "  s1.src = '/system/doom/static/soundfont-player.min.js';\n"
            + "  s1.onload = function() { _sfReady = true; _initPercussion(); };\n"
            + "  s1.onerror = function() { console.warn('[Music] soundfont-player failed to load'); };\n"
            + "  document.head.appendChild(s1);\n"
            + "}\n"
            + "\n"
            // ── Audio context lifecycle ─────────────────────────────────────────
            + "container.addEventListener('click', function() {\n"
            + "  if (!audioContext) { initAudio(); }\n"
            + "  else if (audioContext.state === 'suspended') { audioContext.resume(); }\n"
            + "});\n"
            + "window.addEventListener('focus', function() {\n"
            + "  if (audioContext && audioContext.state === 'suspended') audioContext.resume();\n"
            + "});\n"
            + "document.addEventListener('visibilitychange', function() {\n"
            + "  if (!document.hidden && audioContext && audioContext.state === 'suspended') audioContext.resume();\n"
            + "});\n"
            + "\n"
            // ── Match status poll (drives lobby overlay + deferred stream start) ──
            + "var streamStarted = false;\n"
            + "function pollMatchStatus() {\n"
            + "  fetch('/system/doom/match/status' + _matchParams)\n"
            + "    .then(function(r) { return r.json(); })\n"
            + "    .then(function(s) {\n"
            + "      matchStatusEl.textContent = s.running\n"
            + "        ? ('LIVE | ' + s.joined + '/' + s.players + ' players')\n"
            + "        : ('Waiting... ' + s.joined + '/' + s.players);\n"
            + "      if (lobbyCount) lobbyCount.textContent = s.joined + ' / ' + s.players + ' players joined';\n"
            + "      if (lobbyOverlay && s.joined >= s.players && !lobbyOverlay.classList.contains('hidden')) {\n"
            + "        lobbyOverlay.classList.add('hidden');\n"
            + "        container.focus();\n"
            + "      }\n"
            + "      if (s.running && !streamStarted) {\n"
            + "        streamStarted = true;\n"
            + "        frameImg.src = '/system/doom/match/frame/stream' + _matchParams;\n"
            + "        _connectWS();\n"
            + "      }\n"
            + "    }).catch(function() {});\n"
            + "}\n"
            + "setInterval(pollMatchStatus, 500);\n"
            + "\n"
            + "container.focus();\n"
            + "pollMatchStatus();\n"
            + "console.log('DOOM Deathmatch ready. Match: ' + MATCH_ID + ' Slot: ' + PLAYER_SLOT);\n"
            + "</script>\n"
            + "</body></html>";
    }

    private static String escapeHtml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
